<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Order;
use App\Parametrization;
use App\ProductCategory;
use App\Product;
use Redirect,Response,DB,Config;
use Mail;
use App\Mail\OrderCreated;
class TestController extends Controller
{
    public function index()
    {
			$order = new Order();
			$order->card_email="luise.ruelasz@gmail.com";
			Mail::to($order->card_email)->send(new OrderCreated($order));
			exit();
			// $queryBuilderProducts = \DB::table('products')->where('active', 1)->where('product_category_id', '!=', 9);
			\DB::table('products')->insert([ 'img' => '7 Flores Extracto Grevill ML.png', 'name' => '7 Flores Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Toronjil, Tila americana, Tila trompo, Tila estrella, Zapote blanco, Azahar de naranjo, Flor de manita.  Relajante especial para niños y adolescentes  BENEFICIO DE SUS INGREDIENTES  Ayuda en problemas de insomnio  Útil en problemas de nerviosismo  Útil en ansiedad  Tranquilizante natural ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Acem Capsulas  Grevill ML.png', 'name' => 'Acem Capsulas  Grevill', 'price_mxn' => '330', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Raíz de Echinacea, Cebolla, Palo de Arco, Hierba del cáncer, quinquefolius americano, Zarzaparrilla  BENEFICIO DE SUS INGREDIENTES  Aumenta las defensas inmunológicas contra virus-bacterias  Ayuda a impedir la multiplicación celular en caso de células malignas y tumores  Auxilia en infecciones que provocan ganglios inflamados  Ayuda a prevenir del VPH y miomas uterinos  Anticancerígeno ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Adol Extracto  Grevill ML.png', 'name' => 'Adol Extracto  Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Garra del diablo, Enebro, Sauce Blanco, Diente de León, Ulmaria  BENEFICIO DE SUS INGREDIENTES  Producto natural elaborado a base de plantas analgésicas, especialmente para dolores articulares, musculares, ligamentos y otros dolores. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Afroxzinc Capsulas  Grevill ML.png', 'name' => 'Afroxzinc Capsulas  Grevill', 'price_mxn' => '310', 'description' => '30 cápsulas INGREDIENTES PRINCIPALES:  Tribulus, L-Arginina, Zinc  BENEFICIO DE SUS INGREDIENTES  Aumenta la potencia sexual  Mejora eyaculación precoz  Fortalece espermatozoides débiles  Aumenta la testosterona  Aumenta la energía mental y corporal  Aumenta su libido ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Ajoceb Capsulas Grevill ML.png', 'name' => 'Ajoceb Capsulas Grevill', 'price_mxn' => '115', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Ajo, Cebolla  Mejora la circulación y disminuye la presión arterial  BENEFICIO DE SUS INGREDIENTES  Desintegra la grasa circulante y adherida en vasos sanguíneos  Disminuye colesterol, triglicéridos y ácido úrico  Evita la formación de coágulos en arterias y venas  Fortalece arterias y venas evitando dolores musculares de miembros inferiores o dolores de cabeza.  Mejora su circulación de miembros inferiores  Apoya a evitar la arteriosclerosis y aterosclerosis.  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Ajoceli Jarabe Grevill ML.png', 'name' => 'Ajoceli Jarabe Grevill', 'price_mxn' => '80', 'description' => 'Jarabe 120ml INGREDIENTES PRINCIPALES:  Miel de abeja, extracto de ajo, Cebolla, Limón, Echinacea, Bugambilia, Gordolobo.   BENEFICIO DE SUS INGREDIENTES  Fortalece las vías respiratorias  Desinflamante de amígdalas Desinflama amígdala, faringe, laringe.  Mejora garganta irritada  Auxilia en gripe aguda o crónica  Útil en caso de tos y bronquitis  Excelente jarabe para niños  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Antibin Wereke Tabletas Grevill ML.png', 'name' => 'Antibin Wereke Tabletas Grevill', 'price_mxn' => '165', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Wereke, Cebolla, Hidrastide  BENEFICIO DE SUS INGREDIENTES  Disminuye la glucosa alta en sangre  Mejora el funcionamiento del páncreas e hígado  Fortalece las células productoras de insulina  Mejora el funcionamiento del páncreas ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'ATX-N Extracto Grevill ML.png', 'name' => 'ATX-N Extracto Grevill', 'price_mxn' => '190', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Chelidonia, Cola de caballo, Diente de León, Hierba del sapo,  Zarzaparrilla, Palo de Brasil  BENEFICIO DE SUS INGREDIENTES  Elimina toxinas en la sangre, en hígado y riñones  Disminuye el colesterol adherido en vasos sanguíneos  Elimina el ácido úrico anormal en sangre  Elimina la retención de líquidos  Auxilia en alergias de piel provocadas por alimentación, medicamentos o picadura de insecto  Purificador Sanguíneo ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Avir Tabletas Grevill ML.png', 'name' => 'Avir Tabletas Grevill', 'price_mxn' => '370', 'description' => '90 Tabletas INGREDIENTES PRINCIPALES:  Ajo, Raíz de Echinacea, Golden seal, Zarzaparrilla, Hierba de San Juan  BENEFICIO DE SUS INGREDIENTES  Fortalece vías inmunes  Auxilia en infecciones virales y bacterianas  Inhibe la reproducción de virus de papiloma humano y herpes zoster  Previene la infección por hongos en vías genitales  Fortalece el hígado en caso de hepatitis por cualquier virus  Especial contra gripes e infecciones de mucosa oral por virus  Antiviral  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Bilical Extracto Grevill ML.png', 'name' => 'Bilical Extracto Grevill', 'price_mxn' => '92', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Diente de león, Milenrama, Agracejo, Boldo, Chelidonia  BENEFICIO DE SUS INGREDIENTES  Mejora el metabolismo de hígado y funcionamiento de Vesícula biliar  Previene de formar cálculos biliares o lodo biliar  Aumenta la calidad de bilis para mejorar la digestión  Desinflama la vesícula Biliar  Excelente desinflamante de Vesícula Biliar ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Bilical Tabletas Grevill ML.png', 'name' => 'Bilical Tabletas Grevill', 'price_mxn' => '160', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Diente de león, Milenrama, Agracejo, Boldo, Chelidonia  BENEFICIO DE SUS INGREDIENTES  Mejora el metabolismo de hígado y funcionamiento de Vesícula biliar  Previene de formar cálculos biliares o lodo biliar  Aumenta la calidad de bilis para mejorar la digestión  Desinflama la vesícula Biliar  Excelente desinflamante de Vesícula Biliar ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Boldanhi Capsulas Grevill ML.png', 'name' => 'Boldanhi Capsulas Grevill', 'price_mxn' => '115', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Boldo, Eneldo, Hinojo, Cedrón  BENEFICIO DE SUS INGREDIENTES  Asiste a la acidez estomacal nocturna  Ayuda en caso de digestión lenta  Auxilia en caso de diarrea no infecciosa.  Apoya en espasmos digestivos. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Boldo Extracto Grevill ML.png', 'name' => 'Boldo Extracto Grevill', 'price_mxn' => '62', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES: Boldo, Menta, Diente de León BENEFICIO DE SUS INGREDIENTES Aumenta la producción de bilis para una digestión optima Auxilia el mal sabor de boca o seca Mejora el metabolismo del hígado', 'active' => 1]);
\DB::table('products')->insert([ 'img' => '.png', 'name' => 'Bronxil Extracto Grevill', 'price_mxn' => '98', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Echinacea purpura, Quinquefolius americano, Hidrastis Canadiense, Hojas de eucalipto  BENEFICIO DE SUS INGREDIENTES  Ayuda a fortalecer las defensas del cuerpo  Fortalece vías respiratorias (Garganta, Amígdalas, bronquios y pulmones)  Útil para gripe, inflamación de garganta y tos.  Auxilia para expectorar la flema acumulada en la mucosa de vías respiratorias  Auxiliar en Amigdalitis crónica, Bronquitis y Asma. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Bronxil Tabletas Grevill ML.png', 'name' => 'Bronxil Tabletas Grevill', 'price_mxn' => '175', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Echinacea purpura, Quinquefolius americano, Hidrastis Canadiense, Hojas de eucalipto  BENEFICIO DE SUS INGREDIENTES  Ayuda a fortalecer las defensas del cuerpo  Fortalece vías respiratorias (Garganta, Amígdalas, bronquios y pulmones)  Útil para gripe, inflamación de garganta y tos.  Auxilia para expectorar la flema acumulada en la mucosa de vías respiratorias  Auxiliar en Amigdalitis crónica, Bronquitis y Asma. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Cabursi Tabletas Grevill ML.png', 'name' => 'Cabursi Tabletas Grevill', 'price_mxn' => '130', 'description' => '75 Tabeltas INGREDIENTES PRINCIPALES:  Cola de caballo, Enebro, Hojas de Uva Ursi  BENEFICIO DE SUS INGREDIENTES  Aumenta el volumen de orina excretada  Auxilia en infecciones renales y vejiga  Ayuda en edema de miembros inferiores  Auxilia en arenillas y cálculos renales  Auxilia en infecciones renales y vejiga ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Calcio de Coral Capsulas Grevill ML.png', 'name' => 'Calcio de Coral Capsulas Grevill', 'price_mxn' => '290', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Calcio de coral, Sulfato de Condrotina, Sulfato de Glucosamina,  Cartílago de Tiburón.  Fortalece huesos y articulaciones  BENEFICIO DE SUS INGREDIENTES  Calcifica y fortalece sus huesos en la adolescencia y juventud  Auxilia para prevenir calambres musculares  Fortalece huesos en pacientes embarazadas  Útil en casos de fisuras óseas  Fortalece la columna vertebral  Auxilia en artritis y osteoporosis. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Cartilago de Tiburon Extracto Grevill ML.png', 'name' => 'Cartilago de Tiburon Extracto Grevill', 'price_mxn' => '155', 'description' => 'Extracto 60ml INGREDIENTES PRINCIPALES:  Ajo, Calcio de coral, Cartílago de Tiburón, Harpagofito, Sulfato de Condrotina BENEFICIO DE SUS INGREDIENTES  Prepara para la concentración de calcio y cartílago de los huesos  Desinflama articulaciones dañadas por artritis  Fortalece huesos débiles  Auxilia en dolores musculares. Auxiliar en dolores de huesos y articulaciones ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Castaño de Indias Extracto Grevill ML.png', 'name' => 'Castaño de Indias Extracto Grevill', 'price_mxn' => '87', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Castaño de Indias, Hamamelis, Ginkgo balaba  BENEFICIO DE SUS INGREDIENTES  Mejora la circulación periférica aumentando la concentración de nutrientes y oxígeno  Evita que las piernas se tornen oscuras indicando mala circulación  Fortalece capas musculares de las venas evitando inflamación  Evita grasa adherida en las venas previniendo comezón y ardor  Excelente para desinflamar hemorroides ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'CBL Capsulas Grevill ML.png', 'name' => 'CBL Capsulas Grevill', 'price_mxn' => '275', 'description' => '90 Cápsulas INGREDIENTES PRINCIPALES:  Cardo Mariano, Agracejo, Agrimonia, Romero, Ajenjo, Cola de caballo  BENEFICIO DE SUS INGREDIENTES  Ayuda a evitar la formación de cálculos biliares  Desinflama la vesícula biliar  Aumenta la calidad de bilis y previene el lodo biliar  Mejora la digestión evitando estreñimiento  Auxilia en metabolismo de grasas  Previene la obesidad  Excelente en vesícula biliar y metabolismo de hígado  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'CBVT Tabletas Grevill ML.png', 'name' => 'CBVT Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Ácido glutámico, Ginkgo Biloba, Jengibre, Levadura de Cerveza  Mejora la memoria y la concentración  BENEFICIO DE SUS INGREDIENTES  Nutriente cerebral especial  Oxigenador y relajador cerebral  Induce al cuerpo a relajarse y tener un sueño reparador  Auxilia en la concentración mental y mantiene la confianza en uno mismo. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Cefal Tabletas Grevill ML.png', 'name' => 'Cefal Tabletas Grevill', 'price_mxn' => '190', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Ácido glutámico, Flor de lúpulo, Flor de alhucema,  Flor tila americana, Zapote Blanco.  BENEFICIO DE SUS INGREDIENTES  Especial para dolores de cabeza  Mejora la circulación de cabeza y cuello  Evita la pesadez y cansancio cerebral  Auxilia evitando el insomnio Relajante cerebral y nutriente nervioso ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Chotryg-Deg Tabletas Grevill ML.png', 'name' => 'Chotryg-Deg Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Palo de Brasil, Avena, Diente de león, Cardo mariano, Cebolla.  BENEFICIO DE SUS INGREDIENTES  Disminuye grasas circulantes en sangre  Mejora el metabolismo de lípidos en hígado evitando  acumulación en tejidos  Evita que los tóxicos que entran al cuerpo dañen las células  Apoya para evitar de padecer trombosis o coágulos. Disminuye colesterol y triglicéridos altos en Sangre  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'CLN Capsulas Grevill ML.png', 'name' => 'CLN Capsulas Grevill', 'price_mxn' => '115', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Aloe Vera, Hoja Sen, Cáscara Sagrada, Fenogreco BENEFICIO DE SUS INGREDIENTES  Aumenta la peristalsis intestinal  Auxilia en caso de estreñimiento  Limpia el colon de rezagos intestinales  Aumenta la cantidad de bolo fecal, ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Colageno Plus Capsulas Grevill ML.png', 'name' => 'Colageno Plus Capsulas Grevill', 'price_mxn' => '180', 'description' => '30 Cápsulas INGREDIENTES PRINCIPALES:  Colágeno, Glucosamina, Vitamina C, Coenzima Q10, Jalea Real, Vitamina E, Ácido Cítrico  BENEFICIO DE SUS INGREDIENTES  Fortalece articulaciones y columna vertebral  Auxilia en mantener la elasticidad de tendones, Músculos y ligamentos  Regenera el cartílago del cuerpo  Evita el gastamiento articular, tobillos, rodillas, cadera y manos  Aumenta la energía celular evitando cansancio crónico  Especial para fortalecer huesos y articulaciones ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Colageno Polvo Grevill ML.png', 'name' => 'Colageno Polvo Grevill', 'price_mxn' => '330', 'description' => 'Polvo 450gr INGREDIENTES PRINCIPALES:  Colágeno Proteicos, ácido cítrico, Vitamina C, Coenzima Q10, Sabor frutos rojos  BENEFICIO DE SUS INGREDIENTES  Previene la vejez prematura  Aumenta la energía neuronal y corporal  Mantiene la elasticidad muscular  Elimina celulitis en piel  Especial para la piel, uñas y cabello  Regenera Cartílagos, Tejido Conectivo, Músculos, Articulaciones ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Condromine Capsulas Grevill ML.png', 'name' => 'Condromine Capsulas Grevill', 'price_mxn' => '305', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Sulfato de glucosamina, Sulfato de Condrotina, Cebolla, Tricalcio, Colágeno.  Fortalece huesos y regulariza el colágeno  BENEFICIO DE SUS INGREDIENTES  Especial para fortalecer cualquier articulación del cuerpo (Rodillas, Tobillos, Cadera, Columna vertebral, Etc.)  Fortalece músculos, tendones, ligamentos y tejido conectivo  Auxilia en artritis deformante  Apoya para evitar osteopenia y osteoporosis  Consolida fracturas en cualquier hueso  Previene el desgaste de cartílago ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'C-Ossein-T Tabletas Grevill ML.png', 'name' => 'C-Ossein-T Tabletas Grevill', 'price_mxn' => '149', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Cartílago de Tiburón, Cebolla, Sulfato de glucosamina, Zarzaparrilla  BENEFICIO DE SUS INGREDIENTES  Fortalece músculos, ligamentos, tendones y huesos  Especial para personas adultas y de la 3ra edad  Apoya para prevenir daño articular por artritis o gota  Auxilia en artritis reumatoide deformante en etapa inicial  Disminuye ácidos circulantes en sangre ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Coul-F Tabletas Grevill ML.png', 'name' => 'Coul-F Tabletas Grevill', 'price_mxn' => '170', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES: Fenogreco, Fecula de Papa, Hidrastide Especial para casos de estreñimiento BENEFICIO DE SUS INGREDIENTES Evita los espasmos intestinales y gastricos Desinflama y regenera mucosa de colon Auxilia en casos de colitis aguda y crónica. Foralece las capas musculares de colon Auxilia en diverticulos intestinales.', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Cuacahbol Extracto Grevill ML.png', 'name' => 'Cuacahbol Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Manzanilla, Menta, Cuachalalate, Salvia. BENEFICIO DE SUS INGREDIENTES  Mejora la digestión lenta  Expulsa gases intestinales  Equilibra la digestión  Auxilia en caso de espasmos gastro-intestinales.  Ayuda en gástritis agudas y crónicas. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Cuachabol Te Grevill ML.png', 'name' => 'Cuachabol Te Grevill', 'price_mxn' => '75', 'description' => '120gr INGREDIENTES PRINCIPALES:  Manzanilla, Menta, Cuachalalate, Salvia. BENEFICIO DE SUS INGREDIENTES  Mejora la digestión lenta  Expulsa gases intestinales  Equilibra la digestión  Auxilia en caso de espasmos gastro-intestinales.  Ayuda en gastritis agudas y crónicas. Equilibra la digestión ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Curcuma Capsulas Grevill ML.png', 'name' => 'Curcuma Capsulas Grevill', 'price_mxn' => '200', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Cúrcuma, Jengibre, Menta, Moringa  BENEFICIO DE SUS INGREDIENTES  Mejora la circulación central y periférica  Aumenta las defensas inmunológicas  Aumenta el oxígeno circulante evitando la oxidación en las células corporales  Puede ayudar a prevenir de padecer vértigo o mareos  Ayuda en casos de acidez sanguínea y dolor musculares por ácido úrico (Reumatismo)  Antioxidante y circulatorio  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Cx-Osser Capsulas Grevill ML.png', 'name' => 'Cx-Osser Capsulas Grevill', 'price_mxn' => '460', 'description' => '90 Cápsulas INGREDIENTES PRINCIPALES:  Sulfato de Glucosamina. Sulfato de Condroitina, Colágeno,  Cartílago de Tiburón, Cebolla  BENEFICIO DE SUS INGREDIENTES  Fortalece huesos y cartílagos  Auxilia en dolores musculares crónicos  Calambres musculares  Auxilia en osteoporosis y deterioro de cartílagos.  Brinda mejor elasticidad en articulaciones, músculos, tendones y ligamentos ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Degrazzi Capsulas Grevill ML.png', 'name' => 'Degrazzi Capsulas Grevill', 'price_mxn' => '240', 'description' => '90 Cápsulas INGREDIENTES PRINCIPALES:  Alcachofa, Lecitina de Soya, Cayenne, L-Arginina, Ajo, Cebolla, Diente de león.  BENEFICIO DE SUS INGREDIENTES  Auxilia en hígado graso  Desintegra grasas circulantes y grasas adheridas como ateromas  Auxilia en quistes de grasa (Lipomas)  Puede ayudar a prevenir de trombosis cerebral  Desintegra grasas adheridas en arterias coronarias  Degradador de grasas ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Depress Forte Capsulas Grevill ML.png', 'name' => 'Depress Forte Capsulas Grevill', 'price_mxn' => '260', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Toronjil, Kava-Kava, Hierba de San Juan, Pasiflora, Zapote Blanco. BENEFICIO DE SUS INGREDIENTES  Equilibra la captación de serotonina  Relaja los musculos de cuello y columna  Relaja médula espinal  Desaparece los deseos de llorar y tristeza  Libera la tensión del sistema nervioso autónomo  Elimina el cansancio cerebral y el insomnio  Ayuda a aumentar la lucidez mental Especial para depresión nerviosa y ansiedad. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Depress Forte Extracto Grevill ML.png', 'name' => 'Depress Forte Extracto Grevill', 'price_mxn' => '140', 'description' => 'Extracto 60ml INGREDIENTES PRINCIPALES:  Toronjil, Kava-Kava, Hierba de San Juan, Pasiflora, Zapote Blanco.   BENEFICIO DE SUS INGREDIENTES  Equilibra la captación de serotonina  Relaja los músculos de cuello y columna  Relaja médula espinal  Desaparece los deseos de llorar y tristeza  Libera la tensión del sistema nervioso autónomo  Elimina el cansancio cerebral y el insomnio  Aumenta la lucidez mental Auxilia en depresión nerviosa y ansiedad ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Dequist Extracto Grevill ML.png', 'name' => 'Dequist Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Ajo, Cebolla, Milenrama, Diente de León, Zarzaparrilla, Uña de gato  BENEFICIO DE SUS INGREDIENTES  Ayuda a degrada quistes de mama y ovarios  Desinflama ganglios hipertrofiados  Auxilia en hongos e inflamaciones de mucosa vaginal  Ayuda a desintegrar miomas incipientes  Útil en quistes y miomas  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Dequist Tabletas Grevill ML.png', 'name' => 'Dequist Tabletas Grevill', 'price_mxn' => '172', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Ajo, Cebolla, Milenrama, Diente de León, Zarzaparrilla, Uña de gato  BENEFICIO DE SUS INGREDIENTES  Ayuda a degrada quistes de mama y ovarios  Desinflama ganglios hipertrofiados  Auxilia en hongos e inflamaciones de mucosa vaginal  Ayuda a desintegrar miomas incipientes  Útil en quistes y miomas  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Diabex Extracto Grevill ML.png', 'name' => 'Diabex Extracto Grevill', 'price_mxn' => '140', 'description' => 'Extracto 60ml INGREDIENTES PRINCIPALES:  Tronadora, Hojas de olivo, Wereke, Neem  BENEFICIO DE SUS INGREDIENTES  Disminuye glucosa en sangre  Ayuda al páncreas  Disminuye el sabor amargo en boca  Mejora la producción de insulina  Disminuye glucosa en sangre ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Digesbrha Capsulas Grevill ML.png', 'name' => 'Digesbrha Capsulas Grevill', 'price_mxn' => '115', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Eneldo, Anís verde, Menta Verde, Cardamomo, Hinojo, Cedrón.  BENEFICIO DE SUS INGREDIENTES  Elimina exceso de gases intestinales  Digestión lenta y perezosa  Auxilia en inflamacion gastro-intestinal  Elimina acidez estomacal  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Echiprol Extracto Grevill ML.png', 'name' => 'Echiprol Extracto Grevill', 'price_mxn' => '98', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Raíz de Echinacea, Propóleo, Rosa castilla  BENEFICIO DE SUS INGREDIENTES  Auxilia en infecciones de garganta aguda o crónica  Bronquitis aguda o crónica  Amígdalas con inflamación frecuente  Tos crónica Auxilia en Bronquitis y amígdalas con inflamación frecuente ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Epilfort Tabletas Grevill ML.png', 'name' => 'Epilfort Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Ruda, Jengibre, Tila bolita, Pasiflora, Zapote Blanco.  BENEFICIO DE SUS INGREDIENTES  Auxiliar en personas que padecen convulsiones epilépticas  Mejora Tics nerviosos  Auxilia en nerviosismo con hormigueo en brazos y piernas  Relajante cerebral e inductor del sueño en casos de insomnios  Relaja la médula espinal y base del cráneo  Relaja cerebro y médula espinal ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Eutusil Jarabe Grevill ML.png', 'name' => 'Eutusil Jarabe Grevill', 'price_mxn' => '120', 'description' => 'Jarabe 240ml INGREDIENTES PRINCIPALES:  Echinacea purpurea, Gordolobo, Borraja, Propóleo, Esencia de eucalipto  BENEFICIO DE SUS INGREDIENTES  Auxilia en inflamación de vías respiratorias  Fortalece vías respiratorias (Garganta, Amígdalas, bronquios y pulmones)  Auxilia en gripe, alergias, rinitis.  Auxilia en tos, bronquitis, asma Auxiliar en amigdalitis crónica, Bronquitis y Asma.', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Eutusil Te Grevill ML.png', 'name' => 'Eutusil Te Grevill', 'price_mxn' => '75', 'description' => '120gr INGREDIENTES PRINCIPALES:  Eucalipto, Rosa de Castilla, Orégano BENEFICIO DE SUS INGREDIENTES  Auxilia en inflamación de vías respiratorias  Fortalece vias respiratorias (Garganta, Amígdalas, bronquios y pulmones)  Auxilia en gripe, alergías, rinitis.  Auxilia en tos, bronquitis, asma Auxiliar en amigdalitis crónica, Bronquitis y Asma. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Extrapul Jugo Extracto Grevill ML.png', 'name' => 'Extrapul Jugo Extracto Grevill', 'price_mxn' => '210', 'description' => 'Extracto 500ml INGREDIENTES PRINCIPALES:  Flor de tusilago, Flor sauco, Flor de Echinacea, Flor de lobelia, Flor de bugambilia,  Fruto Noni, Eucalipto, Miel de abeja, Canela, Raíz de tejocote, Raíz de hidrastis canadiense  BENEFICIO DE SUS INGREDIENTES  Auxilia a expulsar flemas  Fortalece bronquios y pulmones  Ayuda a prevenir de inflamación bronquial en tiempo de frio  Fortalece las defensas inmunológicas  Auxilia en problemas de asma bronquial Fortalece bronquios y pulmones     ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Flenogel Gel Grevill ML.png', 'name' => 'Flenogel Gel Grevill', 'price_mxn' => '150', 'description' => 'Gel 120ml INGREDIENTES PRINCIPALES:  Castaño de indias, Colágeno Hidrolizado, Mentol, Hamamelis  BENEFICIO DE SUS INGREDIENTES  Relajante muscular, tendones, ligamentos y articulaciones  Evita la mala circulación e inflamación de venas  Útil para golpes musculares o dolor por contracturas musculares  Relajante de músculos, vertebras y cuello  Relaja el dolor de venas principalmente de miembros inferiores Relajante Muscular, Tendones, Ligamentos, Articulaciones ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Flenor Capsulas Grevill ML.png', 'name' => 'Flenor Capsulas Grevill', 'price_mxn' => '240', 'description' => '90 Cápsulas INGREDIENTES PRINCIPALES:  Ginkgo Biloba, Castaño de Indias, Hamamelis, Zarzaparrilla, Cebolla,  Cola de Caballo, Milenrama  BENEFICIO DE SUS INGREDIENTES  Auxilia a desinflamar varices y hemorroides  Mejora la circulación periférica y cerebral  Apoya a prevenir la formación de varices  Puede apoyar a evitar la formación de coágulos sanguíneos  Desintegra el colesterol adherido en venas y arterias  Aumenta el oxígeno en sangre Normaliza circulación y venas ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Foviz Capsulas Grevill ML.png', 'name' => 'Foviz Capsulas Grevill', 'price_mxn' => '225', 'description' => '90 Cápsulas INGREDIENTES PRINCIPALES:  Betacaroteno, Rutina, Ginkgo Biloba, Levadura de Cerveza, Eufrasia.  BENEFICIO DE SUS INGREDIENTES  Fortalece la vista cansada  Mejora la microcirculación de la retina  Aumenta la oxigenación del ojo  Fortalece el nervio óptico  Especial para ayudar a la vista cansada  Auxilia a mejorar la visión de noche ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Gartox Spray Grevill ML.png', 'name' => 'Gartox Spray Grevill', 'price_mxn' => '99', 'description' => 'Spray 40ml INGREDIENTES PRINCIPALES:  Extracto de: Propóleo, Echinacea, Hidrastis Canadiense, Orégano  BENEFICIO DE SUS INGREDIENTES  Auxilia en inflamaciones de garganta (Amigdalitis, Faringitis)  Ayuda evitando la ronquera  Útil en comezón de garganta y tos  Previene que microbios bacterianos o virales viajen en la mucosa de vías respiratorias  Ayuda en algunos casos de bronquitis aguda  Útil en adultos y menores.  Auxilia en inflamaciones de garganta  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Gastrocoul Tabletas Grevill ML.png', 'name' => 'Gastrocoul Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Fenogreco, Salvia, Hidrastis Canadiense. BENEFICIO DE SUS INGREDIENTES  Auxilia en gastritis aguda y crónica.  Disminuye dolor gástricos por estrés.  Ayuda en úlceras gastro-duodenal.  Regenera mucosa gástrica.  Apoya en infecciones gastrointestinales. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Glum-T Capsulas Grevill ML.png', 'name' => 'Glum-T Capsulas Grevill', 'price_mxn' => '230', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Vitamina B1, Vitamina B3, Vitamina B12, Levadura de Cerveza,  Jalea Real, Gotu kola, Ácido glutámico.  BENEFICIO DE SUS INGREDIENTES  Evita las crisis de ansiedad y estrés  Mejora la memoria fortaleciendo las neuronas  Evita el cansancio de cuello y base cerebral (Occipital)  Ayuda a la memoria y lucidez mental en personas con depresión  Mejora el rendimiento intelectual ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Goldchin Extracto Grevill ML.png', 'name' => 'Goldchin Extracto Grevill', 'price_mxn' => '180', 'description' => 'Extracto 60ml INGREDIENTES PRINCIPALES:  Cebolla, Lampazo chino, Propóleo, Raíz de Echinacea, Raíz de Golden seal  BENEFICIO DE SUS INGREDIENTES  Útil en infecciones agudas y crónicas  Auxilia en Amigdalitis, Faringitis, Bronquitis, Tos, Gripe  Especial para infecciones vaginales (Hongos y virus)  Auxilia en caso de candida albicans  Útil en herpes simple y zoster  Aumenta las defensas inmunológicas  Útil en casos de dengue y enfermedades virales  Útil en infecciones virales o bacterianas ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Goldchin Spray Grevill ML.png', 'name' => 'Goldchin Spray Grevill', 'price_mxn' => '150', 'description' => 'Spray 120ml INGREDIENTES PRINCIPALES:  Allium Sativum, Berberina, Pimienta negra, Raíz de hydrastis, Alcohol de caña.  BENEFICIO DE SUS INGREDIENTES  Inhibe la reproducción de microbios en la mucosa respiratoria  Neutraliza bacterias, Virus y hongos en las manos.  Neutraliza tóxicos ambientales que respiramos  Expulsa moco acumulado en vías respiratorias  Desinflama mucosa oral y respiratoria inhibiendo la reproducción de virus y bacterias.  Spray antibacterial', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Grazzi Capsulas Grevill ML.png', 'name' => 'Grazzi Capsulas Grevill', 'price_mxn' => '245', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Garcinia de Camboya, L-carnitine, Lecitina de soya, L-Arginina, Ácido alfalipoico  BENEFICIO DE SUS INGREDIENTES  Auxilia en casos de sobrepeso y obesidad  Desintegra grasas acumuladas en cualquier parte del cuerpo  Disminuye el apetito causado por ansiedad  Convierte la grasa en energía.  Especial para sobrepeso y obesidad  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Grazzi Te Grevill ML.png', 'name' => 'Grazzi Te Grevill', 'price_mxn' => '75', 'description' => '120gr INGREDIENTES PRINCIPALES:  Diente de León, Alcachofa, Canela, Jengibre, Cola de caballo, Cúrcuma, Cocolmeca, Hoja de limón.  BENEFICIO DE SUS INGREDIENTES  Auxilia en casos de sobrepeso y obesidad  Desintegra grasas acumuladas en cualquier parte del cuerpo  Disminuye el apetito causado por ansiedad  Convierte la grasa en energía.  Especial para sobrepeso y obesidad  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Hepabor -C Tabletas Grevill ML.png', 'name' => 'Hepabor -C Tabletas Grevill', 'price_mxn' => '115', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Amargón, Boldo, Cuasia, Menta piperita, Romero  BENEFICIO DE SUS INGREDIENTES  Fortalece el hígado  Auxilia en caso de Hepatitis  Apoya a evitar inflamación de vesícula biliar  Puede ayudar a prevenir Cirrosis Hepática  Elimina el mal aliento y mal sabor de la boca  Ayuda a desaparecer manchas de la cara  Especial para metabolismo de Hígado ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Hepacir Capsulas Grevill ML.png', 'name' => 'Hepacir Capsulas Grevill', 'price_mxn' => '210', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Boldo, Cardo mariano, Diente de león, Milenrama, Romero  BENEFICIO DE SUS INGREDIENTES  Equilibra el metabolismo de hígado  Puede ayudar a prevenir Cirrosis hepática  Auxilia en caso de hepatitis  Mejora el metabolismo del hígado en personas alcohólicas  Aumenta la calidad de la bilis evitando el estreñimiento  Fortalece el Hígado y su metabolismo ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Histal Extracto Grevill ML.png', 'name' => 'Histal Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Equinácea, Cebolla, Nogal, Flor de sauco, Perejil, Raíz de Zarzaparrilla  BENEFICIO DE SUS INGREDIENTES  Auxilia en alergia bronquial  Expulsa tóxicos de vías respiratorias  Apoya a prevenir la inflamación de mucosa resporatoria  Ayuda a evitar la faringuitis viral  Especial para alergías ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'IGX Capsulas Grevill ML.png', 'name' => 'IGX Capsulas Grevill', 'price_mxn' => '290', 'description' => '90 Cápsulas INGREDIENTES PRINCIPALES:  Wereke, Moringa, Neem, Tronadora, Ginseng, Cardo mariano, Ácido alfa-lipoico  Especial para diabetes  BENEFICIO DE SUS INGREDIENTES  Disminuye la cantidad de glucosa alta circulante  Fortalece páncreas e hígado  Puede ayudar a prevenir el envejecimiento precoz de órganos en personas diabéticas  Reduce el deseo excesivo de comer ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Jengibre Te Grevill ML.png', 'name' => 'Jengibre Te Grevill', 'price_mxn' => '120', 'description' => '120gr INGREDIENTES PRINCIPALES:  Cúrcuma, Jengibre, Hoja de limón, Hojas de menta verde  BENEFICIO DE SUS INGREDIENTES  Anti-inflamatorio abdominal  Contribuye a la pérdida de apetito  Mejora la digestión  Antioxidante  Auxilia en aparato respiratorio  Mejora circulación  Útil en caso de mareos y oxigenación cerebral  Desinflamante y antioxidante ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Junone Jugo Extracto Grevill ML.png', 'name' => 'Junone Jugo Extracto Grevill', 'price_mxn' => '210', 'description' => 'Extracto 500ml INGREDIENTES PRINCIPALES:  Jugo extracto de Noni  BENEFICIO DE SUS INGREDIENTES  Fortalece bronquios y pulmones  Relaja nervios y cerebro  Fortalece la inmunología del cuerpo  Auxilia a prevenir de padecer diabetes  Ayuda a prevenir el desarrollo de células anormales  Aumenta la energía corporal  Fortalece la inmunología del cuerpo ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Lupuval Extracto Grevill ML.png', 'name' => 'Lupuval Extracto Grevill', 'price_mxn' => '87', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Lúpulo, Pasiflora, Espliego, Toronjil, Damiana California  BENEFICIO DE SUS INGREDIENTES  Auxilia a relajar el sistema nervioso central y periférico  Combate el insomnio agudo o crónico  Inductor del sueño ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Mangoringa Jugo Extracto Grevill ML.png', 'name' => 'Mangoringa Jugo Extracto Grevill', 'price_mxn' => '140', 'description' => 'Jugo Extracto 500ml INGREDIENTES PRINCIPALES:  Extracto Jugo Noni, Mangostán, Moringa  BENEFICIO DE SUS INGREDIENTES  Aumenta las defensas inmunológicas en pacientes débiles  Fortalece las vías respiratorias  Mejora la calidad de sangre corporal  Aumenta la energía corporal  Fortalece el cerebro y los nervios  Disminuye la agresividad de la gripe y tos  Fortalece las vías respiratorias y aumenta energía corporal ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Mentas Extracto Grevill ML.png', 'name' => 'Mentas Extracto Grevill', 'price_mxn' => '62', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Albahacar, Menta blanca, Menta verde, hierbabuena BENEFICIO DE SUS INGREDIENTES  Mejora mal sabor de boca  Disminuye gases y espasmos intestinales  Auxilia en dolor de estomago  Ayuda a mejorar la digestión  Acelera peristaltismo gastro-intestinal. ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'MGS Tabletas Grevill ML.png', 'name' => 'MGS Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Toronjil, Pasiflora, Romero, Levadura de Cerveza, Ácido glutámico  Previene y auxilia en Migrañas  BENEFICIO DE SUS INGREDIENTES  Mejora la migraña nerviosa  Auxilia en cansancio y pesadez cerebral  Mejora la migraña frontal y tics nerviosos  Relaja los nervios de cerebro  Previene el cansancio y dolor ocular ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Milenrama Extracto Grevill ML.png', 'name' => 'Milenrama Extracto Grevill', 'price_mxn' => '62', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Milenrama (Achillea millefolium)  BENEFICIO DE SUS INGREDIENTES  Evita sangrados anormales como: Hemorragias menstruales, hemorroides, sangrados nasales y heridas sangrantes  Actúa como anti-inflamatorio  Previene mala digestión como gases intestinales o diarreas Útil en sangrado anormal ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Miotum Capsulas Grevill ML.png', 'name' => 'Miotum Capsulas Grevill', 'price_mxn' => '245', 'description' => '90 Cápsulas INGREDIENTES PRINCIPALES:  Milenrama, Nogal, Diente de León, Zarzaparrilla, Uña de gato  BENEFICIO DE SUS INGREDIENTES  Auxilia a desintegrar miomas de útero, quistes de mama y ovarios  Purifica la sangre aumentando el oxígeno en el órgano con miomas y quistes  Desinflama ovarios  Auxilia en ganglios inflamados  Puede ayudar a prevenir de cáncer cervicouterino  Degrada miomas, quistes y tumores benignos *Puede ayudar a degradar miomas, quistes y tumores benignos ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Moringa Capsulas Grevill ML.png', 'name' => 'Moringa Capsulas Grevill', 'price_mxn' => '200', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Moringa, Mangostan, Noni  BENEFICIO DE SUS INGREDIENTES  Ayuda a fortalecer páncreas  Fortalece vías respiratorias  Fortalece el páncreas  Aumenta las defensas inmunológicas  Auxilia en debilidad corporal  Disminuye la glucosa en sangre ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Moringa Jarabe Grevill ML.png', 'name' => 'Moringa Jarabe Grevill', 'price_mxn' => '120', 'description' => 'Jarabe 240ml INGREDIENTES PRINCIPALES:  Moringa, Mangostán, Noni, Eucalipto, Limón, Miel de abeja  BENEFICIO DE SUS INGREDIENTES  Excelente auxiliador de tos crónica y bronquitis  Disminuye los síntomas de la gripe aguda  Ayuda en casos de rinitis alérgica estacional  Auxilia en faringitis  Auxilia en tos crónica y bronquitis  Disminuye crisis de asma y comezón en garganta  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Neoxigen Extracto Grevill ML.png', 'name' => 'Neoxigen Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES: Vitamina B1, Ácido glutámico, Cebolla, Jalea Real, Ginkgo Biloba BENEFICIO DE SUS INGREDIENTES Mejora la circulación cerebral relajando vasos sanguíneos Mejora la memoria y concentración Auxilia en cansancio y dolor cerebral Ayuda a evitar trombosis cerebral Agudiza el intelecto y lucidez mental', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Neoxigen Tabletas Grevill ML.png', 'name' => 'Neoxigen Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES: Vitamina B1, Ácido glutámico, Cebolla, Jalea Real, Ginkgo Biloba BENEFICIO DE SUS INGREDIENTES Mejora la circulación cerebral relajando vasos sanguíneos Mejora la memoria y concentración Auxilia en cansancio y dolor cerebral Ayuda a evitar trombosis cerebral Agudiza el intelecto y lucidez mental', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Neurosom Tabletas Grevill ML.png', 'name' => 'Neurosom Tabletas Grevill', 'price_mxn' => '205', 'description' => '50 Tabletas INGREDIENTES PRINCIPALES:  Vitamina B6, Vitamina B12, Coenzima Q10, Lecitina de soya  Ácido glutámico.  BENEFICIO DE SUS INGREDIENTES  Aumenta la lucidez mental  Evita la somnolencia mental y pesadez cerebral  Mejora la capacidad de percepción  Aumenta la energía cerebral y corporal.  Aumenta la concentración de oxígeno y glucosa en cerebro ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Noaror Capsulas Grevill ML.png', 'name' => 'Noaror Capsulas Grevill', 'price_mxn' => '115', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Espino blanco, Zapote Blanco, Tila trompo, Ajo.  BENEFICIO DE SUS INGREDIENTES  Auxilia a normalizar la presión arterial alta  Aumenta el oxígeno en corazón y cerebro  Apoya a evitar taquicardias  Mejora la circulación cerebral y periférica  Auxilia en angina de pecho Normaliza la presión sanguínea alta ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Nvs Extracto Grevill ML.png', 'name' => 'Nvs Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Alhucema, Pasiflora, Tila Bolita, Tila trompo, Toronjil.  BENEFICIO DE SUS INGREDIENTES  Relajante de columna vertebral  Auxilia en casos de nerviosismo  Auxilia en casos de insomnio agudo y crónico  Ayuda al estrés causado por trabajo intelectual  No genera dependencia  Poderoso tranquilizante natural ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'NVS Tabletas Grevill ML.png', 'name' => 'NVS Tabletas Grevill', 'price_mxn' => '115', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Alhucema, Pasiflora, Tila Bolita, Tila trompo, Toronjil.  BENEFICIO DE SUS INGREDIENTES  Relajante de columna vertebral  Auxilia en casos de nerviosismo  Auxilia en casos de insomnio agudo y crónico  Ayuda al estrés causado por trabajo intelectual  No genera dependencia  Poderoso tranquilizante natural ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'OCG Tabletas Grevill ML.png', 'name' => 'OCG Tabletas Grevill', 'price_mxn' => '255', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Cartílago de tiburón, Ginseng siberiano, Olmo americano, Raíz de barchata, Uña de gato.  BENEFICIO DE SUS INGREDIENTES  Degradador de algunos tipos de células malignas  Auxilia en quistes de mama y ovarios  Desintegra quistes de riñones  Le auxilia en cáncer maligno no metastásico  *Puede ayudar a degradar quistes y tumores en una etapa incipiente  Degrada quistes y tumores en una etapa incipiente*  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Oculfort Tabletas Grevill ML.png', 'name' => 'Oculfort Tabletas Grevill', 'price_mxn' => '147', 'description' => '50 Tabletas INGREDIENTES PRINCIPALES:  Vitamina A, Vitamina C, Vitamina E, Ginkgo biloba, Jengibre. BENEFICIO DE SUS INGREDIENTES  Oxigenador y vasodilatador ocular  Aumenta la concentración de oxígeno en retina  Evita formar coágulos en el ojo  Evita las cataratas incipientes  Mejora el cansancio ocular  Ayuda a prevenir la presbicia precoz Permite mejor circulación y nutrición ocular ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Omezin 3-6-9 Grevill ML.png', 'name' => 'Omezin 3-6-9 Grevill', 'price_mxn' => '154', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  OMEGA 3. 6. 9, Zinc, Lecitina de soya, Fucus, Ajo, Cúrcuma  BENEFICIO DE SUS INGREDIENTES  Mejora la circulación corporal  Disminuye el colesterol y triglicéridos circulantes  Mejora la concentración de oxígeno en cerebro y cuerpo  Evita la acumulación de colesterol  Auxilia a desintegrar grasas acumuladas ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'OXI Capsulas Grevill ML.png', 'name' => 'OXI Capsulas Grevill', 'price_mxn' => '180', 'description' => '30 Cápsulas INGREDIENTES PRINCIPALES:  Vitamina A, Vitamina C, Lucuma, Camu-Camu, Acai, Goji  BENEFICIO DE SUS INGREDIENTES  Purificador sanguíneo evitando la oxidación celular  Aumenta la concentración de oxígeno celular  Neutraliza tóxicos en hígado, riñones y sangre  Aumenta la energía corporal  Evita el cansancio muscular y fatiga crónica  Antioxidante ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Palmitto Capsulas Grevill ML.png', 'name' => 'Palmitto Capsulas Grevill', 'price_mxn' => '310', 'description' => '90 Cápsulas INGREDIENTES PRINCIPALES:  Palmitto silvestre, Cola de caballo, Pingüica, Zarzaparrilla, Raíz de Ortíga  BENEFICIO DE SUS INGREDIENTES  Aumenta la excreción de flujo urinario.  Previene el desarrollo de células cancerígenas en próstata  Desaparece el goteo urinario y relaja la vejiga para orinar mejor  Aumenta la potencia al orinar  Útil en prostatitis benigna  Especial para desinflamar próstata  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Pasiflora Extracto Grevill ML.png', 'name' => 'Pasiflora Extracto Grevill', 'price_mxn' => '62', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES: Pasiflora Especial para nerviosismo BENEFICIO DE SUS INGREDIENTES Ayuda en nerviosismo agudo o crónico Auxilia para evitar ansiedad Útil para relajación cerebral y corporal', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Propoleo Extracto Grevill ML.png', 'name' => 'Propoleo Extracto Grevill', 'price_mxn' => '100', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Propóleo, Rosa de Castilla  BENEFICIO DE SUS INGREDIENTES  Fortalece el sistema inmunológico  Desinflama amígdalas hipertrofiados  Mejora garganta irritada  Auxilia en gripe aguda o crónica  Útil en caso de bronquitis aguda  Desinflamante de amígdalas  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Prosaw-C Tabletas Grevill ML.png', 'name' => 'Prosaw-C Tabletas Grevill', 'price_mxn' => '155', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Cartílago de tiburón, Uva ursi, Saw palmetto, Cola de caballo  BENEFICIO DE SUS INGREDIENTES  Auxilia en problemas de próstata inflamada  Aumenta la potencia al orinar  Disminuye la sensación de ardor al orinar  Útil para desinflamar próstata ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Psoderm Capsulas Grevill ML.png', 'name' => 'Psoderm Capsulas Grevill', 'price_mxn' => '200', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Ginkgo biloba, Echinacea purpurea, Gotu kola, Algas marianas, Diente de León  BENEFICIO DE SUS INGREDIENTES  Auxilia a prevenir manchas en piel  Regenerar piel en quemaduras solares  Útil para fortalecer la piel en caso de psoriasis  En caso de Celulitis ayuda a regenerar su piel Oxigena, regenera heridas y cicatrices en la piel ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'RCLL Capsulas Grevill ML.png', 'name' => 'RCLL Capsulas Grevill', 'price_mxn' => '260', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Vitamina A, Vitamina C, Vitamina E, Levadura de Cerveza, Coenzima Q10, Jalea Real, Panax Ginseng.  BENEFICIO DE SUS INGREDIENTES  Auxilia a regenerar células y eliminar radicales libres  Antioxidante especial  Especial para aumentar la energía  Regenerador articular, celular, orgánico  Ayuda a prevenir vejez prematura  Antioxidante celular ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'R-Menstabs Tabletas Grevill ML.png', 'name' => 'R-Menstabs Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Nogal, Milenrama, Ortiga Orégano.  BENEFICIO DE SUS INGREDIENTES  Regula el periodo menstrual  Desaparece sangrados anormales  Desinflama Ovarios  Auxilia en cólicos menstruales  Regulador Menstrual ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Rn-Cal Capsulas Grevill ML.png', 'name' => 'Rn-Cal Capsulas Grevill', 'price_mxn' => '195', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Bayas de enebro, Cola de caballo, Hierba del sapo, Raíz de ortiga, Rompepiedras  BENEFICIO DE SUS INGREDIENTES  *Auxilia a expulsar arenillas, sedimentos y desintegra cálculos renales  Aumenta el volumen urinario,  Mejora la filtración renal  Auxilia en caso de Insuficiencia renal aguda  Disminuye dolores renales  Aumenta la excreción de urea alta en sangre  Desintegra arenillas y cálculos renales*  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Sabal Pros Extracto Grevill ML.png', 'name' => 'Sabal Pros Extracto Grevill', 'price_mxn' => '175', 'description' => 'Extracto 60ml INGREDIENTES PRINCIPALES:  Raíz de Echinacea, Palmitto, Cartílago de tiburón  BENEFICIO DE SUS INGREDIENTES  Mejora el volumen urinario  Ayuda a desinflamar próstata  Disminuye el dolor de la micción  Mejora la potencia en la micción  Elimina células malignas en próstata  Útil para problemas de próstata ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Salmofin Capsulas Grevill ML.png', 'name' => 'Salmofin Capsulas Grevill', 'price_mxn' => '260', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Semilla de alholva, Raíz de hidrastide, Romero, Albahacar, Menta.  BENEFICIO DE SUS INGREDIENTES  Regenera mucosa de colon  Cicatriza úlceras gástricas  Útil en gastritis y colitis  Ayuda en caso de ácidez estomacal  Evita la entrada de germenes bacterianos al estómago e intestino ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Smilax Extracto Grevill ML.png', 'name' => 'Smilax Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Diente de León, Nogal, Muicle, Zarzaparrilla, Palo de Brasil  BENEFICIO DE SUS INGREDIENTES  Purificador sanguíneo de tóxicos y grasas adheridas.  Disminuye la concentración de ácido úrico en la sangre, colesterol y triglicéridos altos  Excelente auxiliador contra alergias alimenticias, por medicamentos y alergias que se reflejan en piel Purifica la sangre de toxinas ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Tagocol Tabletas Grevill ML.png', 'name' => 'Tagocol Tabletas Grevill', 'price_mxn' => '118', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Cola de caballo, Enebro, Uva Ursi, Taray, Hierba del sapo  BENEFICIO DE SUS INGREDIENTES  Disminuye edema de miembros inferiores  Aumenta el volumen urinario  Previene de infecciones en vías urinarias  Desaparece el ardor, dolor e inflamación de vejiga al orinar  Útil en ardor en la planta de los pies  Purifica los riñones de impurezas adheridas en ellos  Desinflama riñones y vejiga urinaria ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'THJA Extracto Grevill ML.png', 'name' => 'THJA Extracto Grevill', 'price_mxn' => '190', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  THUJA  BENEFICIO DE SUS INGREDIENTES  Útil en papiloma humano  Auxilia a desaparecer mezquinos o verrugas  Auxilia en caso de virus  Útil para problemas de piel  Ayuda en problemas de piel ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Tonico Jicaro Guiro Compuesto Grevill ML.png', 'name' => 'Tonico Jicaro Guiro Compuesto Grevill', 'price_mxn' => '125', 'description' => 'Tonico 240ml INGREDIENTES PRINCIPALES:  Jícaro, Raíz de Echinacea, Flor de tusilago, Flor de bugambilia,  Hojas de Eucalipto, Hojas de Orégano, Raíz de Jengibre, Miel de abeja.  BENEFICIO DE SUS INGREDIENTES  Fortalece sistema inmunológico  Auxilia la debilidad de bronquios y pulmones evitando las alergias principalmente  Ayuda a evitar las alergias respiratorias frecuentes  Fortalece la mucosa respiratoria a cumplir sus funciones de respiración y expulsión de moco.  Fortalece vías respiratorias  ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Tronap Capsulas Grevill ML.png', 'name' => 'Tronap Capsulas Grevill', 'price_mxn' => '115', 'description' => '60 Cápsulas INGREDIENTES PRINCIPALES:  Boldo, Neem, Nopal, Prodigiosa, Tronadora.  BENEFICIO DE SUS INGREDIENTES  Estimula el páncreas para producir insulina de calidad  Regula la glucosa alta en sangre  Auxilia a la sensación de boca amarga y seca  Es efectiva para diabetes mellitus  Estimula el metabolismo del páncreas ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Ucal Extracto Grevill ML.png', 'name' => 'Ucal Extracto Grevill', 'price_mxn' => '87', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Doradilla, Enebro, Ortiga, Uva Ursi  BENEFICIO DE SUS INGREDIENTES  Elimina edema generalizado  Mejora la filtración renal  Elimina cálculos renales y arenillas  Aumenta el flujo urinario  Expulsa residuo urinario de vejiga  Útil en insuficiencia renal aguda  Expulsa arenillas y cálculos renales ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Uñigat Extracto Grevill ML.png', 'name' => 'Uñigat Extracto Grevill', 'price_mxn' => '87', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Uña de gato, Zarzaparrilla, Cebolla BENEFICIO DE SUS INGREDIENTES  Elimina toxinas en sangre  Mejora el dolor e inflamaciones articulares  Aumenta la elasticidad articular  Útil en disminuir acidez sanguínea  Puede ayudar a prevenir reumatismo y dolores musculares  Auxilia a prevenir la generación de vasos sanguíneos en tumores evitando su expansión ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Uñigat Tabletas Grevill ML.png', 'name' => 'Uñigat Tabletas Grevill', 'price_mxn' => '149', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Uña de gato, Zarzaparrilla, Cebolla BENEFICIO DE SUS INGREDIENTES  Elimina toxinas en sangre  Mejora el dolor e inflamaciones articulares  Aumenta la elasticidad articular  Útil en disminuir acidez sanguínea  Puede ayudar a prevenir reumatismo y dolores musculares  Auxilia a prevenir la generación de vasos sanguíneos en tumores evitando su expansión ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Urideg Extracto Grevill ML.png', 'name' => 'Urideg Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Ajo, Cebolla, Diente de León, Papa, Ulmaria  BENEFICIO DE SUS INGREDIENTES  Auxilia en reumatismo y artritis  Ayuda en dolores musculares  Desinflama articulaciones  Purifica la sangre de ácido úrico  Mejora el dolor articular  Elimina ácido úrico alto en sangre ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Urideg Tabletas Grevill ML.png', 'name' => 'Urideg Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Ajo, Cebolla, Diente de León, Papa, Ulmaria  BENEFICIO DE SUS INGREDIENTES  Auxilia en reumatismo y artritis  Ayuda en dolores musculares  Desinflama articulaciones  Purifica la sangre de ácido úrico  Mejora el dolor articular  Elimina ácido úrico alto en sangre ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Venodol Tabletas Grevill ML.png', 'name' => 'Venodol Tabletas Grevill', 'price_mxn' => '129', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Cancerina, Encino, Ginkgo biloba, Mikania, Palo de Brasil  BENEFICIO DE SUS INGREDIENTES  Mejora la circulación general desde cerebro hasta miembros inferiores  Evita acumulo de grasas adheridas en venas previniendo varices y úlceras varicosas  Previene calambres musculares  Auxilia en caso de hemorroides y venas varicosas Evita comezón e inflamación de venas ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Vitalidad Capsulas Grevill ML.png', 'name' => 'Vitalidad Capsulas Grevill', 'price_mxn' => '280', 'description' => '30 Cápsulas INGREDIENTES PRINCIPALES:  Coenzima Q-10, Jalea Real, Ginseng Panax  BENEFICIO DE SUS INGREDIENTES  Fortalece el sistema inmunológico en general  Aumenta la oxigenación cerebral manteniendo el estado de alerta óptimo en cerebro  Útil en pacientes diabéticos previniendo cansancio muscular y cerebral  Aumenta la energía corporal  Le auxilia en síndrome de fatiga crónica  Disminuye el estrés  Sí el cansancio es diario, recobra la energía del cuerpo  Aumenta la energía corporal ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'XYZ Forte Tabletas Grevill ML.png', 'name' => 'XYZ Forte Tabletas Grevill', 'price_mxn' => '255', 'description' => '90 Tabletas INGREDIENTES PRINCIPALES:  Damiana de california, Polen de flores, Jalea Real, Levadura de cerveza  BENEFICIO DE SUS INGREDIENTES  Aumenta la potencia sexual  Mejora la eyaculación precoz en hombres  Fortalece espermatozoides débiles en hombres  Aumenta la energía corporal y mental  Aumenta el deseo sexual  Ayuda a mejorar la circulación  Mejora el desempeño sexual ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Zapote Blanco Extracto Grevill ML.png', 'name' => 'Zapote Blanco Extracto Grevill', 'price_mxn' => '75', 'description' => 'Extracto 120ml INGREDIENTES PRINCIPALES:  Zapote Blanco, Espino Blanco, Flor de manita, Toronjil, Ajo.  Especial para hipertensión arterial.  BENEFICIO DE SUS INGREDIENTES  Auxilia en bajar la presión alta  Evita taquicardias  Ayuda a oxigenar y previene en dolor precordial  Mejora la circulación y oxigenación cerebral  Auxilia en dolores de cabeza por hipertensión ', 'active' => 1]);
\DB::table('products')->insert([ 'img' => 'Zapote Blanco Tabletas Grevill ML.png', 'name' => 'Zapote Blanco Tabletas Grevill', 'price_mxn' => '115', 'description' => '75 Tabletas INGREDIENTES PRINCIPALES:  Zapote Blanco, Espino Blanco, Flor de manita, Toronjil, Ajo.  Especial para hipertensión arterial.  BENEFICIO DE SUS INGREDIENTES  Auxilia en bajar la presión alta  Evita taquicardias  Ayuda a oxigenar y previene en dolor precordial  Mejora la circulación y oxigenación cerebral  Auxilia en dolores de cabeza por hipertensión ', 'active' => 1]);

			// $queryBuilderProducts = \DB::table('products')->where('active', 1)->where('product_category_id', '=', 9);
			// dd($queryBuilderProducts->get());
			// $res = $queryBuilderProducts->update(array("active" => 0));
			// $res = $queryBuilderProducts->delete();
			dd('adding');
		$pc = ProductCategory::find(9);
		$pc->description = "Naturissima farmacia comprometida con la salud de la comunidades ofrece los siguientes servicios de salud.
		<br/>
		<br/>
		<h4>Médico General</h4>
		<ul>
		<li>Consultas médicas: Previa cita en nuestra página <a href=https://www.naturissimafarmacia.com>WEB</a>
		o agendando en la farmacia</li>
		</ul>
		<h4>Naturista y herbolaria</h4>
		<ul>
		<li>Orientación naturista. Previa cita en nuestra página <a href=https://www.naturissimafarmacia.com>WEB</a>
		o agendando en la farmacia en la farmacia
		Horario vespertino de 5 a 7 p.m lunes a viernes.
		Sábado 10 a 1 p. m.</li>
		</ul>
		<h4>Fisioterapia-Rehabilitación</h4>
		<ul>
		<li>Consulta y sesiones de fisioterapia.
		Previa cita en nuestra página <a href=https://www.naturissimafarmacia.com>WEB</a>
		o agendando en la farmacia en la farmacia
		Horario 9 a 7 p.m. Lunes a viernes.
		Sábado 9 a 2 p. m.</li>
		</ul>
		<h4>Acupuntura</h4>
		<ul>
		<li>Consulta y sesiones de acupuntura
		Previa cita en nuestra página <a href=https://www.naturissimafarmacia.com>WEB</a>
		o agendando en la farmacia en la farmacia
		Horario 9 a 7 p.m. Lunes a viernes.
		Sábado 9 a 2 p. m.</li>
		</ul>
		";
    	dd($pc->save());
    	// return redirect()->action("OpenPayController@detalles_de_compra",["id"=>48,"mail-status"=>((Mail::failures())?false:true)]);
    	// return view('test');
//     	$product=Product::where('id',199)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',200)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',204)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',205)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',207)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',209)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',212)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',213)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',214)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',215)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',216)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',217)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',218)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',220)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',221)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',222)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',225)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',226)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',227)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',228)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',229)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',230)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',231)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',232)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',239)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',240)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',241)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',242)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',243)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',244)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',245)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',246)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',247)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',248)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',249)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',250)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',251)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',252)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',253)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',254)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',258)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',259)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',262)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',263)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',264)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',267)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',268)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',269)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',270)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',272)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',273)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',274)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',275)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',279)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',280)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',283)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',284)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',285)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',286)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',287)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',288)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',289)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',290)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',291)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',292)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',293)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',294)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',295)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',296)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',297)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',298)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',300)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',301)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',303)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',306)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',307)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',308)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',309)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',310)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',312)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',313)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',314)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',315)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',316)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',317)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',318)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',319)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',321)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',322)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',323)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',324)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',325)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',327)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',328)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',335)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',336)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',337)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',338)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',339)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',340)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',341)->first(); $product->is_grevill=true;  $product->save();
// $product=Product::where('id',342)->first(); $product->is_grevill=true;  $product->save();


		phpinfo();

    }
}