<?php

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('products')->insert(['name'=>'ACIDO ACETIL CAFEI PVO 10 SOB AZUL', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Acido Acetilsalicilico 850 mg, Cafeina 65 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACIDO ACETIL CAFEI PVO 10 SOB ROJO', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Acido Acetilsalicilico 850 mg, Cafeina 65 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACARBOSA 30 TAB', 'price_mxn'=>'95', 'active'=>true, 'description'=>'Acarbosa 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACEITE BABY JALOMA 60ml P/BEBE', 'price_mxn'=>'12', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACEITE DE ALMENDRAS 60ml', 'price_mxn'=>'10', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACEITE DE COCO 120ml JALOMA', 'price_mxn'=>'30', 'active'=>true, 'description'=>'Aceite de soya, Fragancia, Aceite de coco, Vaselina liquida', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACEITE JALOMA 3 60ML', 'price_mxn'=>'10', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACEITE OLIVO JALOMA 120ml', 'price_mxn'=>'13', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACENIL 10 OVS', 'price_mxn'=>'39', 'active'=>true, 'description'=>'Fluocinolona 500 mcg, Metronidazol 500 mg, Nistatina 100000 UI', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ACIDO ACETIL SALICILICO 30 TAB', 'price_mxn'=>'21', 'active'=>true, 'description'=>'Acido Acetilsalicilico 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ADEVIT  EMULSIÓN 240ML', 'price_mxn'=>'55', 'active'=>true, 'description'=>'Calcio 41.55 mg, Fosforo 32.1 mg, Vitamina A 333 ug, Vitamina D3 2.82 ug, DHA 42.75 mg, EPA 30.75 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ADMIDOXIL 10 CAPS', 'price_mxn'=>'36', 'active'=>true, 'description'=>'Ambroxol 22.5 mg, Dextrometorfano 22.5 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ADOPREN 10 TAB 400 MG', 'price_mxn'=>'19', 'active'=>true, 'description'=>'Ibuprofeno 400 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ADOPREN 10 TAB 600 MG', 'price_mxn'=>'22', 'active'=>true, 'description'=>' Ibuprofeno 600 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ADOPREN 10 TAB 800 MG', 'price_mxn'=>'25', 'active'=>true, 'description'=>'Ibuprofeno 800 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ADRECORT 20 TAB', 'price_mxn'=>'29', 'active'=>true, 'description'=>'Dexametasona 1 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AGUA OXIGENADA JALOMA 224ml', 'price_mxn'=>'8', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ALGIDOL 10 CAPS', 'price_mxn'=>'16', 'active'=>true, 'description'=>'Ibuprofeno 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMBIDRIN', 'price_mxn'=>'43.5', 'active'=>true, 'description'=>'12 CAPS 500 MG (AMPICILINA) ', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMCEF IM 500MG 2 ML', 'price_mxn'=>'48', 'active'=>true, 'description'=>'Ceftriaxona 500 mg, Lidocaina 2 ml', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMCEF IM IG 10ml', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Ceftriaxona 1 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMDORY 14 CAPS', 'price_mxn'=>'80', 'active'=>true, 'description'=>'Lansoprazol 30 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMIKACINA 500MG 2 ML INY', 'price_mxn'=>'42', 'active'=>true, 'description'=>'Amikacina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMIKACINA100MG 2 ML INY', 'price_mxn'=>'24', 'active'=>true, 'description'=>'Amikacina 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMPICILINA 1G 5 ML INY', 'price_mxn'=>'22', 'active'=>true, 'description'=>'Ampicilina 1 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMPICILINA 20 TAB', 'price_mxn'=>'43', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMPICILINA 500MG 2 ML INY', 'price_mxn'=>'17', 'active'=>true, 'description'=>'Ampicilina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMPIGRIN ADULTO C/JERINGAS ', 'price_mxn'=>'133', 'active'=>true, 'description'=>'Ampicilina 500 mg, Clorfenamina 4 mg, Guaifenesina 100 mg, Lidocaina 30 mg, Metamizol Sodico 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMPIGRIN INFANTIL C/JERINGAS ', 'price_mxn'=>'115', 'active'=>true, 'description'=>'3Amp Ampicilina 250 mg, Clorfenamina 2 mg, Guaifenesina 100 mg, Lidocaina 30 mg, Metamizol Sodico 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMPIGRIN PFC 24 CAPS', 'price_mxn'=>'69', 'active'=>true, 'description'=>' Clorfenamina 3 mg, Paracetamol 300 mg, Amantadina 50 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AMPIGRIN PFC JBE 60ML', 'price_mxn'=>'28.5', 'active'=>true, 'description'=>'Clorfenamina 20 mg, Paracetamol 3 g, Amantadina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ANHITEN-A  30 Tab', 'price_mxn'=>'75', 'active'=>true, 'description'=>' Nifedipino 30 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ANTIDOLITO 30 TAB', 'price_mxn'=>'33', 'active'=>true, 'description'=>'Paracetamol 80 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'APONISTAN V 12 TAB', 'price_mxn'=>'35', 'active'=>true, 'description'=>'Nistatina 100000 UI', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ARGEMOL CMA 1% 28 G', 'price_mxn'=>'35', 'active'=>true, 'description'=>'Sulfadiazina de Plata Micronizada 1 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ARTHRIL 15 CAPS', 'price_mxn'=>'52', 'active'=>true, 'description'=>'Ketoprofeno 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ARTROBEN  CMA 60G 5 %', 'price_mxn'=>'58', 'active'=>true, 'description'=>'Bencidamina 5 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ARTROBEN  SPRAY 1 5MG 1 30ML', 'price_mxn'=>'50', 'active'=>true, 'description'=>'Bencidamina 150 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'AZOGEN 20 TAB', 'price_mxn'=>'55', 'active'=>true, 'description'=>'Acido Nalidixico 500 mg, Fenazopiridina 50 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BARMICIL COMP CRA 30gr', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Betametasona 50 mg, Clotrimazol 1 g, Gentamicina 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BERNIVER 2%  UNG 15 G', 'price_mxn'=>'115', 'active'=>true, 'description'=>'Mupirocina 2 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BIBERON 8oz JALOMA POLIPRO SURTIDO', 'price_mxn'=>'13', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BIDROZIL  CMA40 G', 'price_mxn'=>'30', 'active'=>true, 'description'=>' Nistatina 1e+007 UI, Triamcinolona 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BIODERM CREMA 35G', 'price_mxn'=>'59', 'active'=>true, 'description'=>'Aceite de Higado de Bacalao 10 g, Cloruro de Benzalconio 10 mg, Extracto de Hamamelis Virginiana 500 mg, Oxido de Zinc 25 g, Vitamina A 500000 UI, Vitamina D3 90000 UI, Vitamina E 135 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BIOFILEN 28 TAB', 'price_mxn'=>'40', 'active'=>true, 'description'=>'Atenolol 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BIOMESINA COMPUESTA 10 GRAG', 'price_mxn'=>'38', 'active'=>true, 'description'=>'Butilhioscina 10 mg, Metamizol Sodico 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BIOSTAFEX 10 TAB 120MG', 'price_mxn'=>'93', 'active'=>true, 'description'=>'Fexofenadina 120 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BIOSTAFEX 10 TAB 180MG', 'price_mxn'=>'120', 'active'=>true, 'description'=>'Fexofenadina 180 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BIOXOVER  JBE  120 M', 'price_mxn'=>'55', 'active'=>true, 'description'=>'Dropropizina 15 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BLENDOX  JBE 60 ML', 'price_mxn'=>'19.7', 'active'=>true, 'description'=>'Clorfenamina 2.5 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BLUSYVER PRO 14 TAB', 'price_mxn'=>'135', 'active'=>true, 'description'=>'Escitalopram 10 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BONAZIN  GOT 10ML ', 'price_mxn'=>'31', 'active'=>true, 'description'=>'Meclizina 8.33 mg, Vitamina B6 16.66 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BOSNOV 14 TAB 10 MG', 'price_mxn'=>'192', 'active'=>true, 'description'=>'Olanzapina 10 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BOTIQUIN JALOMA GRANDE', 'price_mxn'=>'135', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BRADELMIN1 SUSP 20ML', 'price_mxn'=>'16', 'active'=>true, 'description'=>'Albendazol 2 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BRAX 10 TAB', 'price_mxn'=>'27', 'active'=>true, 'description'=>'Naproxeno 275 mg, Paracetamol 300 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BREALITAM AV SOL 60 ML', 'price_mxn'=>'35', 'active'=>true, 'description'=>'Clorfenamina 1 mg, Fenilefrina 2.75 mg, Paracetamol 150 mg, Amantadina 25 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BREGAMIN  GOT  15 ML', 'price_mxn'=>'20', 'active'=>true, 'description'=>'Clorfenamina 2 mg, Fenilefrina 5 mg, Paracetamol 60 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BREGAMIN  JBE 120 ML', 'price_mxn'=>'21.5', 'active'=>true, 'description'=>'Clorfenamina 1 mg, Fenilefrina 2.5 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BREGAMIN AV  JBE 60ML', 'price_mxn'=>'27.8', 'active'=>true, 'description'=>'Clorfenamina 20 mg, Paracetamol 3 g, Amantadina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BREGAMIN AV PEDIATRICO SOL 30ML ', 'price_mxn'=>'28.7', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BRESALTEC  SUSP AER 200D', 'price_mxn'=>'45.5', 'active'=>true, 'description'=>'Salbutamol 100 mcg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BROMHEXINA AD  SUSP100ML', 'price_mxn'=>'30', 'active'=>true, 'description'=>'Bromhexina 8 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BROMHEXINA INF  SUSP 100ML', 'price_mxn'=>'32', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BROMIXEN 12 CAPS', 'price_mxn'=>'55', 'active'=>true, 'description'=>' Amoxicilina 500 mg, Bromhexina 8 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BROMIXEN 90ml', 'price_mxn'=>'58', 'active'=>true, 'description'=>'Amoxicilina 250 mg, Bromhexina 8 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BROMURO DE PINAVERIO 14TAB', 'price_mxn'=>'60', 'active'=>true, 'description'=>'Bromuro de Pinaverio 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BROSOLAN  SOL 120 ML', 'price_mxn'=>'29', 'active'=>true, 'description'=>'Ambroxol 15 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BRUCAM 20 TAB', 'price_mxn'=>'12', 'active'=>true, 'description'=>'Piroxicam 20 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BRUPACIL BUTILHIOSCINA 10 TAB', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Hioscina 10 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BRYSBAL 10 CAPS ', 'price_mxn'=>'34', 'active'=>true, 'description'=>'Cafeina 100 mg, Ibuprofeno 400 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BUSCONET FA INY', 'price_mxn'=>'37', 'active'=>true, 'description'=>'Butilhioscina 20 mg, Metamizol Sodico 2.5 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'BUTILHIOSCINA 3 AMP 20 MG 1 (BROMURO DE BUTILHIOSCINA) 20200730', 'price_mxn'=>'31', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'C MESSEL 20 TAB', 'price_mxn'=>'18', 'active'=>true, 'description'=>'Vitamina C 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CAPSIFLU TOTAL 12 CAPS', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Dextrometorfano 10 mg, Fenilefrina 5 mg, Paracetamol 250 mg, Bronfeniramina 2 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CAPTOPRIL 30 TAB', 'price_mxn'=>'23', 'active'=>true, 'description'=>'Captopril 25 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CARPIN 20 TAB 200 MG', 'price_mxn'=>'17', 'active'=>true, 'description'=>'Carbamazepina 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CEFALVER 20 CAPS 500MG', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Cefalexina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CEFALVER SUSP 125MG 90 ML', 'price_mxn'=>'39', 'active'=>true, 'description'=>'Cefalexina 125 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CEFALVER SUSP 250MG 90 ML', 'price_mxn'=>'42', 'active'=>true, 'description'=>'Cefalexina 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CELECOXIB 10 CAPS', 'price_mxn'=>'280', 'active'=>true, 'description'=>'Celecoxib 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CEPOBROM SUSP 100ML', 'price_mxn'=>'65', 'active'=>true, 'description'=>' Bromhexina 4.39 mg, Cefalexina 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CEPOBROM 12 CAPS', 'price_mxn'=>'60', 'active'=>true, 'description'=>'Bromhexina 8.782 mg, Cefalexina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CILOCID 20 TAB', 'price_mxn'=>'10', 'active'=>true, 'description'=>'Acido Folico 5 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CINEPRAC 20TAB', 'price_mxn'=>'62', 'active'=>true, 'description'=>'Trimebutina 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CINITAPRIDA 30 SOB 1 MG GRAN', 'price_mxn'=>'152', 'active'=>true, 'description'=>'Cinitaprida 1 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CINTAPORE BCO PXA C/BOLS 1.25 9.2 ', 'price_mxn'=>'14', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CINTAPORE BCO PXA C/BOLS 2.5 9.2', 'price_mxn'=>'27', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CIPROFLOXACINO 12 TAB', 'price_mxn'=>'62', 'active'=>true, 'description'=>'Ciprofloxacino 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CIRULAN  GOT 20 ML ', 'price_mxn'=>'18', 'active'=>true, 'description'=>'Metoclopramida 400 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CIRULAN 20 TAB', 'price_mxn'=>'21', 'active'=>true, 'description'=>'Metoclopramida 10 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLAMOXIN 10 TAB', 'price_mxn'=>'68', 'active'=>true, 'description'=>'Acido Clavulanico 125 mg, Amoxicilina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLAMOXIN 12H 10 TAB', 'price_mxn'=>'83', 'active'=>true, 'description'=>'Acido Clavulanico 125 mg, Amoxicilina 875 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLAMOXIN 12H JR SUSP 50 ML', 'price_mxn'=>'40.5', 'active'=>true, 'description'=>'Acido Clavulanico 57 mg, Amoxicilina 400 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLAMOXIN 12H PEDIATRICO 40ML', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Acido Clavulanico 28.5 mg, Amoxicilina 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLAMOXIN 60ML', 'price_mxn'=>'68', 'active'=>true, 'description'=>'Acido Clavulanico 31.25 mg, Amoxicilina 125 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLAMOXIN S 50ml', 'price_mxn'=>'57', 'active'=>true, 'description'=>'Acido Clavulanico 42.9 mg, Amoxicilina 600 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'LOXINER 10 TAB 125MG', 'price_mxn'=>'33', 'active'=>true, 'description'=>'Clonixinato de Lisina 125 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'LOXINER 10 TAB 250MG', 'price_mxn'=>'54', 'active'=>true, 'description'=>'Clonixinato de Lisina 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLOPIDOGREL 14 TAB', 'price_mxn'=>'95', 'active'=>true, 'description'=>'Clopidogrel 75 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLORANFENICOL UNG 5 G', 'price_mxn'=>'41', 'active'=>true, 'description'=>'Cloranfenicol 5 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLOTRIMAZOL OV', 'price_mxn'=>'85', 'active'=>true, 'description'=>'Clotrimazol 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLOTRIMAZOL DUAL OVS CMA 10G 1%', 'price_mxn'=>'52', 'active'=>true, 'description'=>'Clotrimazol 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CLOTRIMAZOL V  CMA 2% 20 G', 'price_mxn'=>'49', 'active'=>true, 'description'=>'Clotrimazol 2 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CO ALTIVER 15 TAB 25MG 12.5MG', 'price_mxn'=>'70', 'active'=>true, 'description'=>'Captopril 25 mg, Hidroclorotiazida 12.5 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CO ALTIVER 15 TAB 50MG 25MG', 'price_mxn'=>'82', 'active'=>true, 'description'=>'Captopril 50 mg, Hidroclorotiazida 25 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CO EXALIV NF  JBE 120 ML', 'price_mxn'=>'30', 'active'=>true, 'description'=>'Clorfenamina 20 mg, Fenilefrina 100 mg, Guaifenesina 2 g, Paracetamol 2.5 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'COBADEX AD  JBE 120ML', 'price_mxn'=>'22', 'active'=>true, 'description'=>' Ambroxol 225 mg, Dextrometorfano 225 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'COBADEX INF JBE 120ML ', 'price_mxn'=>'23', 'active'=>true, 'description'=>'Ambroxol 150 mg, Dextrometorfano 113 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'COBADEX PEDIA SOL30ML', 'price_mxn'=>'32', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'COLLIFRIN ADULTO  SOL 20ML', 'price_mxn'=>'30', 'active'=>true, 'description'=>'Oximetazolina 50 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'COLSER 30 TAB', 'price_mxn'=>'52', 'active'=>true, 'description'=>'Bezafibrato 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CORDILAT 20 CAPS ', 'price_mxn'=>'28', 'active'=>true, 'description'=>'Nifedipino 10 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CORTIFUNG C  CMA 30 G', 'price_mxn'=>'30', 'active'=>true, 'description'=>'Clioquinol 3 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CRAZTRONIN 3 TAB', 'price_mxn'=>'95', 'active'=>true, 'description'=>'Azitromicina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'CROFERRON 50 TAB', 'price_mxn'=>'30.5', 'active'=>true, 'description'=>'Fumarato Ferroso 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DALATINA GEL TUBO 30G ', 'price_mxn'=>'40', 'active'=>true, 'description'=>'Clindamicina 1 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DEBEQUIN C AD JBE 120ML', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Dextrometorfano 5 mg, Guaifenesina 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DEBEQUIN C INF JBE 120ML', 'price_mxn'=>'35', 'active'=>true, 'description'=>'Dextrometorfano 7.5 mg, Guaifenesina 50 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DEBISOR 20 TAB 10 MG', 'price_mxn'=>'10', 'active'=>true, 'description'=>'Isosorbida 10 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DEBISOR SUBLINGUAL 20 TAB', 'price_mxn'=>'48', 'active'=>true, 'description'=>'Isosorbida 5 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DEFLAZACORT 10 TAB 30 MG ', 'price_mxn'=>'152', 'active'=>true, 'description'=>'Deflazacort 30 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DEFLAZACORT 20 TAB 6 MG', 'price_mxn'=>'112', 'active'=>true, 'description'=>'Deflazacort 6 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DEQUIN GOT 30ML ', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Clorfenamina 20 mg, Fenilefrina 100 mg, Guaifenesina 2 g, Paracetamol 2.5 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DEQUIN JBE 120 ML', 'price_mxn'=>'35', 'active'=>true, 'description'=>'Clorfenamina 1 mg, Fenilefrina 5 mg, Guaifenesina 100 mg, Paracetamol 125 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DERMOVAL CMA 30 G', 'price_mxn'=>'67', 'active'=>true, 'description'=>'Betametasona 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'DOLZYCAM  GEL60 G', 'price_mxn'=>'48', 'active'=>true, 'description'=>'Piroxicam 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ERBITRAX CMA 15 G', 'price_mxn'=>'27', 'active'=>true, 'description'=>'Terbinafina 1 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ERBITRAX CMA 30 G', 'price_mxn'=>'53', 'active'=>true, 'description'=>'Terbinafina 1 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'GEL ANTIBACTERIAL JALOMA 120ml', 'price_mxn'=>'13.5', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'GIMALXINA 12 CAPS', 'price_mxn'=>'35', 'active'=>true, 'description'=>'Amoxicilina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'GIMALXINA 500MG  75ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'Amoxicilina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'GIMALXINA250MG 75 ML ', 'price_mxn'=>'45.5', 'active'=>true, 'description'=>'Amoxicilina 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'INDACIL 16 CAPS', 'price_mxn'=>'95', 'active'=>true, 'description'=>'Clindamicina 300 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'KENZOFLEX GOT 5 ML', 'price_mxn'=>'52', 'active'=>true, 'description'=>'Ciprofloxacino 3 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'KLARIX 10 TAB 250 MG', 'price_mxn'=>'82', 'active'=>true, 'description'=>'Claritromicina 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'KLARIX 10 TAB 500 MG', 'price_mxn'=>'112', 'active'=>true, 'description'=>'Claritromicina 500 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'KROBICIN SUSP 250MG 60 ML', 'price_mxn'=>'129', 'active'=>true, 'description'=>' Claritromicina 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'MACROFURIN 40 CAPS', 'price_mxn'=>'97', 'active'=>true, 'description'=>'Nitrofurantoina 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'MUCOXINA 12 CAPS', 'price_mxn'=>'55', 'active'=>true, 'description'=>'Amoxicilina 500 mg, Bromhexina 8 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'NORECIL 600 20 TAB', 'price_mxn'=>'37', 'active'=>true, 'description'=>'Diyodohidroxiquinoleina 200 mg, Metronidazol 400 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'PENIPOT 400 000 UI', 'price_mxn'=>'19', 'active'=>true, 'description'=>'Bencilpenicilina Procainica 300000 UI, Bencilpenicilina Sodica 100000 UI', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'PENIPOT 800 000 UI', 'price_mxn'=>'23', 'active'=>true, 'description'=>'Bencilpenicilina Procainica 600000 UI, Bencilpenicilina Sodica 200000 UI', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'PENTIBROXIL SUSP 90ml', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Ambroxol 15 mg, Amoxicilina 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'PHENDEX OTICO SUSP 10ml', 'price_mxn'=>'62', 'active'=>true, 'description'=>'Ciprofloxacino 2 mg, Hidrocortisona 10 mg, Lidocaina 50 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'RASPISONS UNG', 'price_mxn'=>'27', 'active'=>true, 'description'=>'Neomicina 350 mg, Vitamina A 100000 UI', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'SICALAN SUSP 30 ML', 'price_mxn'=>'118', 'active'=>true, 'description'=>'Azitromicina 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'SURONIT 12 TAB', 'price_mxn'=>'25', 'active'=>true, 'description'=>'Nitrofurantoina 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TALCO BABY AZUL BOTE 150 G ', 'price_mxn'=>'18', 'active'=>true, 'description'=>'Oxido de Zinc, Talco', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TALCO BABY ROSA BOTE 150 G', 'price_mxn'=>'18', 'active'=>true, 'description'=>'Oxido de Zinc, Talco', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TALCO O-DOLEX AMARILLO 300GR', 'price_mxn'=>'25', 'active'=>true, 'description'=>'Acido Borico, Alcanfor, Benzalconio, Oxido de Zinc, Talco', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TALCO O-DOLEX NATURALS 300GR', 'price_mxn'=>'25', 'active'=>true, 'description'=>'Acido Borico, Cloruro de Benzalconio, Oxido de Zinc, Talco', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TARMIN 12 TAB', 'price_mxn'=>'11', 'active'=>true, 'description'=>'Loperamida 2 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TEMPIRE  GOT 30 ML', 'price_mxn'=>'22', 'active'=>true, 'description'=>'Paracetamol 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TENESCAN  CREMA 20G', 'price_mxn'=>'25', 'active'=>true, 'description'=>'Clotrimazol 1 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TERPLEX 10 TAB', 'price_mxn'=>'82', 'active'=>true, 'description'=>' Fluconazol 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'THRECHOP SUSP 120ML', 'price_mxn'=>'42', 'active'=>true, 'description'=>'Caolin 1 g, Diyodohidroxiquinoleina 62.5 mg, Furazolidona 20 mg, Homatropina 1 mg, Pectina 50 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TOPARAL 30 TAB', 'price_mxn'=>'33', 'active'=>true, 'description'=>'Metildopa 250 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TUSILEN AD  JBE 118ML', 'price_mxn'=>'34', 'active'=>true, 'description'=>'Dextrometorfano 300 mg, Fenilefrina 50 mg, Guaifenesina 2.4 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'TUSILEN PED  JBE 118 ML', 'price_mxn'=>'50', 'active'=>true, 'description'=>'Dextrometorfano 150 mg, Guaifenesina 1.2 g, Paracetamol 3 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'UL FLAM 10 TAB', 'price_mxn'=>'28', 'active'=>true, 'description'=>'Nimesulida 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ULCEVIT  10 GRAG', 'price_mxn'=>'16', 'active'=>true, 'description'=>'Ranitidina 300 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ULGASTRIN 20 GRAG', 'price_mxn'=>'15', 'active'=>true, 'description'=>'Ranitidina 150 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'UREZOL 20 TAB', 'price_mxn'=>'33', 'active'=>true, 'description'=>'Fenazopiridina 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'UROVEC 24 CAPS', 'price_mxn'=>'61', 'active'=>true, 'description'=>'Fenazopiridina 50 mg, Sulfametoxazol 250 mg, Tetraciclina 125 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VALTROVER 20 COMP', 'price_mxn'=>'182', 'active'=>true, 'description'=>'Montelukast 10 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VANESIR 45 TAB ', 'price_mxn'=>'92', 'active'=>true, 'description'=>'Citrus Bioflavonoides 162 mg, Semilla de Uva 30 mg, Vitamina C 150 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VANESIR GEL200 G ', 'price_mxn'=>'84', 'active'=>true, 'description'=>'Ruscus Acuelatus, Hamamelis, Romero, Semilla de Uva, Sabila', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VASDECOM 21 CAPS', 'price_mxn'=>'134', 'active'=>true, 'description'=>'Orlistat 120 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VASELINA JALOMA P/BEBE 60g', 'price_mxn'=>'16', 'active'=>true, 'description'=>' Fragancia, Vaselina Blanca, Petrolato', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VASO ROSCADO ESTERIL PLASTIC WORLD (P/MUESTRA)', 'price_mxn'=>'6', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VELATUSS SOL 120 ML', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Levodropropizina 30 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VENDA ELASTICA 5CM', 'price_mxn'=>'6', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VENDA ELASTICA 7.5CM', 'price_mxn'=>'9', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VENDA ELASTICA CARE 15CM', 'price_mxn'=>'15', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VENDA ELASTICA CARE 5CM', 'price_mxn'=>'6.5', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VENDA ELASTICA IDEAL 10CM', 'price_mxn'=>'11', 'active'=>true, 'description'=>'', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VENGESIC 20 GRAG', 'price_mxn'=>'62', 'active'=>true, 'description'=>'Aluminio Desecado 200 mg, Dexametasona 500 mcg, Fenilbutazona 100 mg, Metocarbamol 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VERATRIN 20 CAPS', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Betametasona 750 mcg, Indometacina 25 mg, Metocarbamol 215 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VERMISEN 2 TAB', 'price_mxn'=>'12', 'active'=>true, 'description'=>'Albendazol 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VERMISEN 6 TAB', 'price_mxn'=>'11', 'active'=>true, 'description'=>'Albendazol 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VIAXOL  GOT 30 ML', 'price_mxn'=>'36', 'active'=>true, 'description'=>'Ambroxol 750 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VISERTRAL SOL 50 ML', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Cetirizina 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VISERTRAL 10 TAB', 'price_mxn'=>'58', 'active'=>true, 'description'=>'Cetirizina 10 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VITACILINA 16G', 'price_mxn'=>'23', 'active'=>true, 'description'=>'Neomicina 350 mg, Vitamina A 100000 UI', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VITACILINA BEBE 50G', 'price_mxn'=>'42', 'active'=>true, 'description'=>' Alantoina 1 g, Oxido de Zinc 25 g, Vitamina A 500000 UI, Vitamina D 90000 UI, Vitamina E 1000 UI', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'Vitacilina Unguento 28 G (SULFATO DE NEOMICINA) 20200830', 'price_mxn'=>'31', 'active'=>true, 'description'=>'Neomicina 350 mg, Palminato de Vitamina A 100000 UI', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VO REMI 5 AMP 1 ML', 'price_mxn'=>'53', 'active'=>true, 'description'=>'Meclizina 25 mg, Vitamina B6 50 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VOLFENAC 1 GEL 60G 16 %', 'price_mxn'=>'29', 'active'=>true, 'description'=>'Diclofenaco Dietilamonio 1.16 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'VOMISIN 3 AMP 50MG 1 ML', 'price_mxn'=>'48', 'active'=>true, 'description'=>'Dimenhidrinato 50 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'WERMY 15 CAPS', 'price_mxn'=>'75', 'active'=>true, 'description'=>'Gabapentina 300 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'YADEGAL COMP  JBE 120 ML', 'price_mxn'=>'40', 'active'=>true, 'description'=>'Clorfenamina 1.5 mg, Dextrometorfano 10 mg, Guaifenesina 100 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'YADEGAL PEDIATRICO GOT 30 M', 'price_mxn'=>'32', 'active'=>true, 'description'=>'Dextrometorfano 275 mg, Guaifenesina 2.25 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'YEMIFER HE 30 TAB', 'price_mxn'=>'42', 'active'=>true, 'description'=>' Acido Folico 1 mg, Fumarato Ferroso 350 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ZISUAL C  ÜNG 30G', 'price_mxn'=>'110', 'active'=>true, 'description'=>'Hidrocortisona 250 mg, Lidocaina 5 g, Oxido de Zinc 18 g, Subacetato de Aluminio 3.5 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ZOLIDIME 20 GRAG', 'price_mxn'=>'87', 'active'=>true, 'description'=>'Aluminio Desecado 200 mg, Dexametasona 500 mcg, Fenilbutazona 100 mg, Salicilamida 200 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ZOLMIC V  CMA 1 % 40 G', 'price_mxn'=>'84', 'active'=>true, 'description'=>'Isoconazol 1 g', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'ZONCONAX  SOL 1% FCO 30 ML', 'price_mxn'=>'43', 'active'=>true, 'description'=>'Terbinafina 888 mg', 'product_category_id'=>1]);
    	DB::table('products')->insert(['name'=>'3 DAMIANAS EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'7 FLORES EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ACEITE MINERAL 120ML', 'price_mxn'=>'31', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ACTIKROLL 100 TAB', 'price_mxn'=>'84', 'active'=>true, 'description'=>'Acido Glutamico 200 mg, Calcio 23 mg, Fosforo 18 mg, Lecitina de Soya 25 mg, Vitamina B1 10 mg, Vitamina B12 20 mg, Vitamina C 20 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ACTIKROLL JBE 250 ML', 'price_mxn'=>'85', 'active'=>true, 'description'=>'Acido Glutamico 10 mg, Glicerofosfato de Sodio 80 mg, Jalea Real 16 mg, Vitamina B1 250 mcg, Vitamina B12 2 mcg, Vitamina B2 2 mg, Vitamina B3 3 mg, Vitamina B5 2 mg, Vitamina B6 3 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ADOL EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'AFRIL EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'AJOCEB 60TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'AJOCELI JBE 120ML', 'price_mxn'=>'60', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ALCACHOFA QUECHOT 30CAPS', 'price_mxn'=>'95', 'active'=>true, 'description'=>'Alcachofa 250 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ALCOFIN EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ALEVARIN 45 CAPS', 'price_mxn'=>'104', 'active'=>true, 'description'=>'Castaño de Indias 166.6 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ALI YABA 30 TAB', 'price_mxn'=>'135', 'active'=>true, 'description'=>'Celulosa Microcristalina, Crosacaramelosa Sodica, Dioxido de Silicio, Estearato de Magnesio, Acido Estearico, Extracto de Guayaba, Arandano', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ANTIBIN WEREKE 75TAB', 'price_mxn'=>'150', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ANTIBIN WEREKE EXT', 'price_mxn'=>'77', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ATXN EXTRACTO 120ML', 'price_mxn'=>'190', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'BILICAL EXTRACTO 120ML', 'price_mxn'=>'77', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'BILICAL TAB 75TAB', 'price_mxn'=>'157', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'BOLDANHI 50TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'BOLDO EXTRACTO 120ML', 'price_mxn'=>'55', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'BRONKITOSE MIELLIMON SAZ JBE 240 ML', 'price_mxn'=>'87', 'active'=>true, 'description'=>'Alcohol Etilico, Bugambilia, Eucalipto, Gordolobo, Limon, Miel, Nipagin, Propilenglicol, Propoleo, Sauco, Maltitol, Nipasol, Amarillo 6', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'BRONXIL EXTRACTO 120ML', 'price_mxn'=>'87', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CABURSI 75TAB ', 'price_mxn'=>'94.5', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CALCAR 120TAB', 'price_mxn'=>'180', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CALTRON 600 + D 60 TAB', 'price_mxn'=>'75', 'active'=>true, 'description'=>'Carbonato de Calcio 1.5 g, Proteinato de Calcio 48 mg, Vitamina D 3.125 mcg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CALTRON FORN K 60 TAB', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Carbonato de Calcio 1.5 g, Proteinato de Calcio 48 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CARTILAGO DE TIBURON EXTRACTO 60ML', 'price_mxn'=>'124', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CASCARA SAGRADA EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CASTAÑO DE INDIAS EXTRACTO 120ML', 'price_mxn'=>'77', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CEFAL 60TAB', 'price_mxn'=>'154', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CEFAL EXTRACTO 120ML', 'price_mxn'=>'103', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CHOTRIG DEG EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CHOTRING DEG 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CLN 75TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CLOROFILA 500ml', 'price_mxn'=>'64', 'active'=>true, 'description'=>'Clorofila 4 g, Menta 200 mg, Mentol 10 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'COLAGENO 60 TAB', 'price_mxn'=>'72', 'active'=>true, 'description'=>'Celulosa Microcristalina, Dioxido de Silicio, Lactosa, Magnesio, Vitamina C 20 mg, Colageno 1 g, Acido Estearico, Croscarmelosa Sodica', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'COLAGENO HIDROLIZADO Y ACEROLA NATUREX', 'price_mxn'=>'160', 'active'=>true, 'description'=>'Acerola 46 mg, Vitamina C 7 mg, Colageno 4 g', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'COMPLEJO B 30 TAB', 'price_mxn'=>'42', 'active'=>true, 'description'=>'Vitamina B1 100 mg, Vitamina B12 50 mcg, Vitamina B6 5 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'COMPLEJO B DIABETICO 30 TAB', 'price_mxn'=>'45', 'active'=>true, 'description'=>'Vitamina B1 100 mg, Vitamina B12 50 mcg, Vitamina B6 5 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CONVIFER C HIERRO SOL 220 ML', 'price_mxn'=>'52', 'active'=>true, 'description'=>'Ciproheptadina 2 mg, Gluconato Ferroso 104.75 mg, Lisina 150 mg, Vitamina B1 5 mg, Vitamina B12 10 mcg, Vitamina B6 7.5 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'COSSEINT 60TAB', 'price_mxn'=>'133', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'COUL F 75TAB', 'price_mxn'=>'177', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'CUACHABOL EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'DEPRES FORTE EXTRACTO 60ML', 'price_mxn'=>'108', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'DEPRESS EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'DEQUIST EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'DIABEX EXTRACTO 60ML', 'price_mxn'=>'108', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'DIGESBRA 50TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'DIGESBRA EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ECHIPROL EXTRACTO 120ML', 'price_mxn'=>'87', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EPAZIT 75TAB', 'price_mxn'=>'106', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EPAZIT EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EPIL FORT EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EPIL FORTE 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EQUIBRON 90TAB', 'price_mxn'=>'217', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EQUIBRON EXT 120ML', 'price_mxn'=>'87', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ETAGERIN 60 COMP', 'price_mxn'=>'98', 'active'=>true, 'description'=>'Extracto de Silimarina 150 mg, Cardo Mariano 187.5 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EUCALIN JBE 240 ML', 'price_mxn'=>'60', 'active'=>true, 'description'=>'Eucalipto 0.375 ml, Gordolobo 0.3875 ml, Mentol 75 mg, Miel 27 g, Mirra 0.275 ml, Propoleo 1.425 ml, Sauco 0.3875 ml', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EUCALIN KIDS JBE 240 ML', 'price_mxn'=>'69', 'active'=>true, 'description'=>'Bugambilia, Eucalipto, Gordolobo, Mentol, Miel, Propoleo, Sauco', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EUTUSIL JBE 240ML', 'price_mxn'=>'87', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EXTRAPUL EXTRACTO 500ML', 'price_mxn'=>'204', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'EXZON 90 TAB 490 MG (FIBRA SOLUBLE DE MAIZVITAMINA C) 20201030', 'price_mxn'=>'125', 'active'=>true, 'description'=>'Citrus Bioflavonoides 120 mg, Lactobacilos 3e+009 SU, Vitamina C 240 mg, Vitamina A 1.8 ug, Vitamina D3 0.03 ug', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'FLEXTRIN 30 COMP', 'price_mxn'=>'107', 'active'=>true, 'description'=>'Condroitina Sulfato 200 mg, Glucosamina 300 mg, Vitamina C 25 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GARTOX SPRAY 40ML ', 'price_mxn'=>'77', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GASTROCOUL 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GASTROCOUL EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GELCAVIT GEM 30 CAPS', 'price_mxn'=>'85', 'active'=>true, 'description'=>'Acido Folico 400 ug, Calcio 50.08 mg, Cobre 1.6 mg, Hierro 10 mg, Licopeno 5 mg, Magnesio 10 mg, Manganeso 3 mg, Niacina 15 mg, Potasio 8.02 mg, Vitamina C 60 mg, Vitamina A 750 ug, Vitamina B1 2 mg, Vitamina B12 6 ug, Vitamina B2 2 mg, Vitamina B5 10.57 mg, Vitamina B6 2 mg, Vitamina D2 10 ug, Vitamina E 300 mg, Zinc 7.5 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GELCAVIT MULIER 30 CAPS', 'price_mxn'=>'92', 'active'=>true, 'description'=>' Aceite de soya, Aceite Vegetal Hidrogenado, Boro, Calcio, Cera de Abejas, Dioxido de Silicio Coloidal, Isoflavonas de Soya, Lecitina de Soya, Magnesio, Niacina, Vitamina A, Vitamina B12, Vitamina B5, Vitamina B6, Vitamina D3, Vitamina E, Zinc', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GLUM T 90TAB', 'price_mxn'=>'217', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GLYCIM F 60TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GOLCHIN EXTRACTO 60ML', 'price_mxn'=>'154', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GRAZZI 60TAB', 'price_mxn'=>'204', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GSG DAY 30 CAP', 'price_mxn'=>'170', 'active'=>true, 'description'=>'Extracto de Panax Ginseng 200 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'GUIRO JBE 240ML', 'price_mxn'=>'111', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'HEPABOR C 75TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'HEPABOR EXT', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'HEPACIR 60TAB', 'price_mxn'=>'201', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'KAMELINA 60 COM', 'price_mxn'=>'62', 'active'=>true, 'description'=>'Extracto Seco de Raiz de Cimicifuga Race 40 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'LACTIV KIDS 30 TAB', 'price_mxn'=>'75', 'active'=>true, 'description'=>'Lactobacilos 333 M UFC, Vitamina C 15 mg, Vitamina D2 1.7 ug', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'LOEV  SUSP 1000 ML', 'price_mxn'=>'120', 'active'=>true, 'description'=>'Extracto de Jengibre 5 mg, Hinojo 1.25 mg, Aloe Vera 0.2 ml', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'LUPUVAL', 'price_mxn'=>'77', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'MANZANILLA EXTRACTO 120ML', 'price_mxn'=>'55', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'MATERFOL 90 COMP', 'price_mxn'=>'39', 'active'=>true, 'description'=>'Acido Folico 400 mcg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'MAXIBILOBA 60 COMP', 'price_mxn'=>'95', 'active'=>true, 'description'=>'Acido Glutamico 250 mg, Calcio 120.24 mg, Ginkgo Biloba 40 mg, Vitamina B1 1.5 mg, Vitamina B12 2 mcg, Vitamina B2 1.7 mg, Vitamina B6 2 mg, Zinc 15 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'MENTAS EXTRACTO 120ML', 'price_mxn'=>'55', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'MGS 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'MGS EXTRACTO 120ML', 'price_mxn'=>'77', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'MILENRAMA EXTRACTO 120ML', 'price_mxn'=>'55', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'MORINGA JBE 240ML', 'price_mxn'=>'120', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'NABIOT EXTRACTO 120ML', 'price_mxn'=>'266', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'NEOXIGEN 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'NEOXIGEN EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'NOARCOR 60TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'NVS 50TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'NVS EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'OXIGIN EXTRACTO 120ML', 'price_mxn'=>'87', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'PASIFLORA EXTRACTO 120ML', 'price_mxn'=>'55', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'PROPOLEO EXTRACTO 120ML', 'price_mxn'=>'87', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'PROSAW 75TAB', 'price_mxn'=>'138', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'PROSTASAN 60 CAPS', 'price_mxn'=>'134', 'active'=>true, 'description'=>'Extracto de Serenoa Repens 160 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'QUERYABA G 60 TAB', 'price_mxn'=>'108', 'active'=>true, 'description'=>'Extracto de Guayaba 22.93 g, Espinheira Santa 30.45 g', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'R MENS EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'R MENS TABS 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'REVENOX 60 TAB ', 'price_mxn'=>'84', 'active'=>true, 'description'=>'Melatonina 3 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'RN CAL 60TAB', 'price_mxn'=>'189', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'SALUFILA SOL 500ML', 'price_mxn'=>'72', 'active'=>true, 'description'=>'Azucar, Carbohidratos 0.06 g, Clorofila 24.51 mg, Cobre 2.63 mg, Grasas, Hierbabuena 0.012 ml, Menta 0.006 ml, Sodio 3.33 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'SITO GRIX JBE 120 ML', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Hiedra 700 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'SMILAX EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'SOYA PROINT BOTE', 'price_mxn'=>'207', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'SOYAPROINT BOLSA (SOYAPROIN) 120G', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'TAGACOL 75TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'TAGOCOL EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'Testalin K 125ML', 'price_mxn'=>'79.9', 'active'=>true, 'description'=>'Acido Citrico, Agua, Benzisotiazolinona, Cloruro de Sodio, Sabila, Cocamidopropil Betaina', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'TRIGONEL 75TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'TRONAP 50TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'TRONAP EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'UCAL EXTRACTO 120ML', 'price_mxn'=>'77', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'UÑIGAT 75TAB', 'price_mxn'=>'139', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'UÑIGAT EXTRACTO 120ML', 'price_mxn'=>'77', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'URIDEG 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'URIDEG EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'V LUTEX 30 TAB', 'price_mxn'=>'35', 'active'=>true, 'description'=>' Cobre 200 ug, Luteina 2.5 mg, Vitamina C 150 mg, Vitamina A 500 ug, Vitamina E 50 mg, Zinc 7.5 mg, Zeaxantina 500 ug', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'VENODOL 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'VENODOL EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'VITAL CEREBRUM (CBVT) 75TAB', 'price_mxn'=>'115', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'VITAL CEREBRUM (CBVT) EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'XYZ Forte', 'price_mxn'=>'242', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ZAFROLAR 30 TAB', 'price_mxn'=>'72', 'active'=>true, 'description'=>'Harpagophitum procumbens 150 mg', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ZAPOTE BLANCO 75TAB', 'price_mxn'=>'105', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ZAPOTE BLANCO EXTRACTO 120ML', 'price_mxn'=>'63', 'active'=>true, 'description'=>'', 'product_category_id'=>3]);
    	DB::table('products')->insert(['name'=>'ALIGOMITAS 60GOMAS', 'price_mxn'=>'82', 'active'=>true, 'description'=>'Acido Folico 104 mcg, Biotina 39 mcg, Colina 14.4 mcg, Inositol 96 mcg, Vitamina A 100 mcg, Vitamina B1 220 mcg, Vitamina B12 2.8 mcg, Vitamina B2 250 mcg, Vitamina B3 3.5 mg, Vitamina B5 2.6 mg, Vitamina B6 600 mcg, Vitamina C 20 mg, Vitamina D 2.6 mcg, Vitamina E 5.4 mg, Yodo 20 mcg, Zinc 1.3 mg', 'product_category_id'=>4]);
    	DB::table('products')->insert(['name'=>'BIG COMPLEX YUMMI 240ML JBE', 'price_mxn'=>'65', 'active'=>true, 'description'=>'Acido Folico, Acido Glutamico, Agua Desmineralizada, Jalea Real, Omega 3, Propilenglicol, Propilparabeno, Sacarosa, Vitamina B1, Vitamina B12, Vitamina B2, Vitamina B6, Pantotenato de Calcio, Jarabe de Agave, Citrato Monosòdico', 'product_category_id'=>4]);
    	DB::table('products')->insert(['name'=>'DENFOR 600 60 COMP', 'price_mxn'=>'185', 'active'=>true, 'description'=>'Calcio 550 mg, Caseinato de Calcio 5 mg, Fosforo 1.8 mg, Magnesio 6.3 mg, Proteinato de Calcio 10 mg, Vitamina D2 5 mcg, Zinc 1.515 mg', 'product_category_id'=>4]);
    	DB::table('products')->insert(['name'=>'DIBENEL MAX 30 CAPS', 'price_mxn'=>'93', 'active'=>true, 'description'=>'Aceite de soya, Acido Folico, Cera de Abejas, Dioxido de Silicio, Gelatina, Glicerina, Lecitina de Soya, Oxido de Magnesio, Policotinato de Cromo, Sulfato de Zinc, Vitamina A, Vitamina B1, Vitamina B12, Vitamina B2, Vitamina B6, Vitamina C, Vitamina E, Selenito de Sodio, Linaza, Chancarro', 'product_category_id'=>4]);
    	DB::table('products')->insert(['name'=>'HUCIUS 30 CAPS', 'price_mxn'=>'134', 'active'=>true, 'description'=>'Extracto seco del rizoma de Ruscus acule 70 mg, Extracto se de semilla de Aesculus 250 mg', 'product_category_id'=>4]);
    	DB::table('products')->insert(['name'=>'MAXI B GS 30 CAPS', 'price_mxn'=>'90', 'active'=>true, 'description'=>'Celulosa Microcristalina, Dioxido de Silicio, Estearato de Magnesio, Extracto de Ginseng, Gluconato de Zinc, Hierro, Inositol, Sulfato de Potasio, Vitamina C, Vitamina A, Vitamina B1, Vitamina B12, Vitamina B2, Vitamina B3, Vitamina B5, Vitamina B6, Vitamina D3, Vitamina E, Fosfato Dibàsico de Calcio', 'product_category_id'=>4]);
    	DB::table('products')->insert(['name'=>'TE CUACHABOL 120G', 'price_mxn'=>'54', 'active'=>true, 'description'=>'', 'product_category_id'=>5]);
    	DB::table('products')->insert(['name'=>'TE EUTUSIL 120G', 'price_mxn'=>'54', 'active'=>true, 'description'=>'', 'product_category_id'=>5]);
    	DB::table('products')->insert(['name'=>'TE JUGLANS 120G', 'price_mxn'=>'54', 'active'=>true, 'description'=>'', 'product_category_id'=>5]);
    	DB::table('products')->insert(['name'=>'TE LIM -TLA 120G', 'price_mxn'=>'54', 'active'=>true, 'description'=>'', 'product_category_id'=>5]);
    	DB::table('products')->insert(['name'=>'TE NVS 120G', 'price_mxn'=>'54', 'active'=>true, 'description'=>'', 'product_category_id'=>5]);
    	DB::table('products')->insert(['name'=>'TE SMILAX 120G', 'price_mxn'=>'54', 'active'=>true, 'description'=>'', 'product_category_id'=>5]);
    	DB::table('products')->insert(['name'=>'TE TAGOCOL 120G', 'price_mxn'=>'54', 'active'=>true, 'description'=>'', 'product_category_id'=>5]);
    	DB::table('products')->insert(['name'=>'TE TRONAP 120G', 'price_mxn'=>'54', 'active'=>true, 'description'=>'', 'product_category_id'=>5]);

    }
}
